Morph subclass: #RubAbstractTextArea
	instanceVariableNames: 'model paragraph editor scrollPane editingState textStyle textColor margins readOnly menuAllowed editingMode cursor segments getMenuPolicy'
	classVariableNames: 'BackgroundColor CaseSensitiveFinds DefaultTextColor LineNumbersBackgroundColor LineNumbersFont LineNumbersTextColor WalkAlongDisplayedLine'
	poolDictionaries: ''
	category: 'Rubric-Editing-Core'