Object subclass: #MorphTreeListManager
	instanceVariableNames: 'keystrokeActionSelector multipleSelection autoMultiSelection potentialDropMorph firstClickedMorph lastClickedMorph columnDropUnabled doubleClickBlock autoDeselection searchedElement lastKeystrokeTime lastKeystrokes lastSelection client isSelectionUpdateFromView isCheckList autoTargetMorph selectedMorphList'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Morphic-Base-MorphTreeWidget'