Object subclass: #MorphTreeListManager
	instanceVariableNames: 'keystrokeActionSelector multipleSelection autoMultiSelection potentialDropMorph firstClickedMorph lastClickedMorph columnDropUnabled autoDeselection searchedElement lastKeystrokeTime lastKeystrokes lastSelection client isSelectionUpdateFromView isCheckList autoTargetMorph selectedMorphList removeOnlyLastSelected doubleClickSelector'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Morphic-Widgets-Tree'