class comment pane
noCommentNagString

	^ 'Unfortunately this class has not been documented yet. The class comment should describe the purpose of the class, its collaborations and its variables. We encourage you to fill up the following template.

Class intention
	I m doing the following ...

Class collaborations
	I usually do not work in isolation but with the help of ...

Class main API
	My main public API is ...My subclasses may want to override such specific hooks ...
Implementation notes
' translated asText
		