Object subclass: #RubTextComposer
	instanceVariableNames: 'lines maxRightX currentY scanner possibleSlide nowSliding prevIndex prevLines currCharIndex startCharIndex stopCharIndex deltaCharIndex theText theContainer isFirstLine theTextStyle defaultLineHeight actualHeight actualWidth numberOfPhysicalLines prevTextStyle prevText prevContainer emphasisHere cursorWidth'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Rubric-Editing-Core'