Object subclass: #OSWindowGLAttributes
	instanceVariableNames: 'redSize blueSize greenSize alphaSize depthSize doubleBuffer swapControl stencilSize minorVersion majorVersion profileType'
	classVariableNames: 'DefaultAlphaSize DefaultBlueSize DefaultDepthSize DefaultDoubleBuffer DefaultGreenSize DefaultMajorVersion DefaultMinorVersion DefaultProfileType DefaultRedSize DefaultStencilSize DefaultSwapControl'
	poolDictionaries: ''
	category: 'OSWindow-Core-OpenGL'