Object subclass: #OSWindowAttributes
	instanceVariableNames: 'animated position extent title fullscreen screenId preferableDriver icon glAttributes windowCentered borderless resizable maximized minimized visible'
	classVariableNames: 'DefaultBorderless DefaultExtent DefaultFullscreen DefaultMaximized DefaultMinimized DefaultPosition DefaultResizable DefaultTitle DefaultVisible DefaultWindowCentered'
	poolDictionaries: ''
	category: 'OSWindow-Core'