AbstractWidgetModel subclass: #TreeModel
	instanceVariableNames: 'childrenBlockHolder menuBlockHolder rootsHolder selectionHolder autoMultiSelection columnInset doubleClick evenRowColor isCheckList keyStroke multiSelection oddRowColor preferedPaneColor resizerWidth rowInset displayBlock columns treeUpdated iconBlock autoDeselection allowMenuOnNoItem rootNodeHolder'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Spec-Core-Widgets'