AbstractWidgetModel subclass: #TreeModel
	instanceVariableNames: 'childrenBlockHolder menuBlockHolder rootsHolder selectionHolder selectedItem autoMultiSelection columnInset doubleClick evenRowColor isCheckList keyStroke multiSelection oddRowColor preferedPaneColor resizerWidth rowInset displayBlock columns treeUpdated iconBlock autoDeselection allowMenuOnNoItem rootNodeHolder removeOnlyLastSelected highlightedItem'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Spec-Core-Widgets'