commentForCurrentUpdate
 ^ '18856 After Epicea integration: "an OmReference(Pharo_2elhj7i:199) not found in OmSessionStore"
	https://pharo.fogbugz.com/f/cases/18856

17710 rename variable do not update class template
	https://pharo.fogbugz.com/f/cases/17710

18855 reduce calls on #compiledMethod in RGMethodDefinition
	https://pharo.fogbugz.com/f/cases/18855

18860 cleanup after running RGMethodDefintionTest
	https://pharo.fogbugz.com/f/cases/18860'