commentForCurrentUpdate
 ^ '19331 ClassRepackaged and MethodRepackaged should be subclassed from ClassAnnouncement and MethodAnnouncement
	https://pharo.fogbugz.com/f/cases/19331

19349 RPackageAnnouncement should be SystemAnnouncement subclass and work as other system changes
	https://pharo.fogbugz.com/f/cases/19349

18881 ChangesBrowser executing refactoring changes in wrong order
	https://pharo.fogbugz.com/f/cases/18881'