commentForCurrentUpdate
 ^ '18624 SlotIntegrationTest>>testSlotScopeParallelism
	https://pharo.fogbugz.com/f/cases/18624

18637 Do not use #name method call in MetacelloPackageSpec>>#workingCopyNameFor:
	https://pharo.fogbugz.com/f/cases/18637

18634 add Object>>perform:with:with:with:with (4 arguments)
	https://pharo.fogbugz.com/f/cases/18634

18347 Extending current selection after double click does not work
	https://pharo.fogbugz.com/f/cases/18347

18604 update kernel manifest 
	https://pharo.fogbugz.com/f/cases/18604'