Model subclass: #ProcessBrowser
	instanceVariableNames: 'selectedProcess selectedContext methodText processList processListIndex stackList stackListIndex selectedClass selectedSelector searchString autoUpdateProcess deferredMessageRecipient lastUpdate startedCPUWatcher keyEventsDict textModel'
	classVariableNames: 'SuspendedProcesses WellKnownProcesses'
	poolDictionaries: ''
	category: 'Tool-ProcessBrowser'