extensions
		
	^ HelpTopic 
		title: 'Extensions'
		contents: 'Spotter allows the developer to define custom search processors in different classes. These custom processors take effect when Spotter reaches an instance of the extended class. You can find below the list of extensions from this image.
		
You can also browse this list by inspecting:

		GTSpotter spotterExtendingMethods

', self extensionsString