doingVSPrinting 
	^ Lesson
title: 'Doing VS Printing: Doing' 
lesson: 
'"Cool ! (I like to say Cooool :) ). You''ve just executed a Smalltalk expression. More precisely, you sent the message ''next'' to ProfStef class (it''s me !).

Note you can run this tutorial again by evaluating: ''ProfStef go''. 
''ProfStef previous'' returns to the previous lesson.

You can also Do It using the keyboard shortcut ''ALT d''
(this varies according to your operating system/computer: it can be ''CMD d'' or ''CTRL d''). 

Try to evaluate these expressions:"

Browser open.

SmalltalkImage current aboutThisSystem.

"Then go to the next lesson:"

ProfStef next.'