printing 
	^ Lesson
title: 'Doing VS Printing: Printing' 
lesson: 
'"Now you''re a Do It master ! Let''s talk about printing. It''s a Do It which prints the result next to the expression you''ve selected.
For example, select the text below, open the menu and click on ''print it (p)'':"

1 + 2.

"You''ve seen the letter ''p'' between parentheses next to ''print it'' ? It indicates the ALT- shortcut to execute this command.

Try ALT-p on the following expressions:"

Date today.

Time now.

"The result is selected, so you can erase it using the backspace key. Try it !"

SmalltalkImage  current datedVersion.

ProfStef next.'