theEnd
	^ Lesson
title: 'Tutorial done !' 
lesson: 
'"This tutorial is done. Enjoy programming with Pharo. 

Don''t forget to read ''Pharo By Example'' found here:  

	http://pharobyexample.org/

You can run this tutorial again by evaluating:"

PharoTutorial go.

"Do you want to create your own interactive tutorial with PharoTutorial ? That''s very easy!!  How ? There''s a PharoTutorial interactive tutorial for that :D
Just evaluate the following code:"

PharoTutorial goOn: HowToMakeYourOwnTutorial

"See you soon !"
'