AbstractTool subclass: #AbstractNautilusUI
	instanceVariableNames: 'model window hierarchyClass cachedHierarchy sourceTextArea sourceCodePanel commentTextArea currentDisplayChoice sourceTextAreaLimit sourceCodeContainer shouldUpdateTitle testSemaphore sourceTextAreas multipleMethodsEditor contentSelection acceptor classifier'
	classVariableNames: 'ClassesIconsCache GroupsIconsCache NextFocusKey PackagesIconsCache PreviousFocusKey'
	poolDictionaries: ''
	category: 'Nautilus'