AbstractTool subclass: #AbstractNautilusUI
	instanceVariableNames: 'model window cachedHierarchy sourceCodePanel fullDisplayedComment sourceCodeContainer shouldUpdateTitle testSemaphore contentSelection acceptor classCommentTextModel commentWidget sourceTextWidget sourceCodeSelectionInterval sourceTextModel'
	classVariableNames: 'NextFocusKey PackagesIconsCache PreviousFocusKey'
	poolDictionaries: ''
	category: 'Nautilus'