AbstractTool subclass: #AbstractNautilusUI
	instanceVariableNames: 'model window cachedHierarchy sourceTextArea sourceCodePanel fullDisplayedComment sourceTextAreaLimit sourceCodeContainer shouldUpdateTitle testSemaphore contentSelection acceptor classifier classCommentTextModel commentWidget'
	classVariableNames: 'ClassesIconsCache GroupsIconsCache NextFocusKey PackagesIconsCache PreviousFocusKey'
	poolDictionaries: ''
	category: 'Nautilus'