commentForCurrentUpdate
 ^ '12619 3 minor fixes
	https://pharo.fogbugz.com/f/cases/12619

12631 methods missing in RPackageTag
	https://pharo.fogbugz.com/f/cases/12631

12634 Update
	https://pharo.fogbugz.com/f/cases/12634

12635 Better mechanism to remove a key based on its shortcut
	https://pharo.fogbugz.com/f/cases/12635

12630 Add ScriptLoader>>#commentForIssues:
	https://pharo.fogbugz.com/f/cases/12630'