commentForCurrentUpdate
 ^ '- issue 12317: Better way to let the user handle missing class when loading code
	https://pharo.fogbugz.com/f/cases/12317/Better-way-to-let-the-user-handle-missing-class-when-loading-code

- issue 12335: Some fixes
	https://pharo.fogbugz.com/f/cases/12335/Some-fixes
	
- issue 12336: Do not open Komitter modal
	https://pharo.fogbugz.com/f/cases/12336/Do-not-open-Komitter-modal'