version434: spec
	<version: '4.34' imports: #('4.1-baseline' )>

	spec for: #'common' do: [
		spec blessing: #'stable'.
		spec description: 'GLMRubricTextPresentation supports #withGhostText: aStringOrText.'.
		spec author: 'JurajKubelka'.
		spec timestamp: '2/18/2017 14:25'.
		spec project: 'FastTable' with: '0.10.7'.
		spec 
			package: 'Glamour-Announcements' with: 'Glamour-Announcements-AndreiChis.8';
			package: 'Glamour-Helpers' with: 'Glamour-Helpers-TudorGirba.40';
			package: 'Glamour-Core' with: 'Glamour-Core-AndreiChis.328';
			package: 'Glamour-Presentations' with: 'Glamour-Presentations-AndreiChis.190';
			package: 'Glamour-Browsers' with: 'Glamour-Browsers-AndreiChis.112';
			package: 'Glamour-Examples' with: 'Glamour-Examples-AndreiChis.319';
			package: 'Glamour-FastTable' with: 'Glamour-FastTable-AndreiChis.75';
			package: 'Glamour-Morphic-Brick' with: 'Glamour-Morphic-Brick-AliakseiSyrel.437';
			package: 'Glamour-Morphic-Brick-Tests' with: 'Glamour-Morphic-Brick-Tests-JurajKubelka.15';
			package: 'Glamour-Tests-Core' with: 'Glamour-Tests-Core-PavelKrivanek.113';
			package: 'Glamour-Tests-Resources' with: 'Glamour-Tests-Resources-AndreiChis.5';
			package: 'Glamour-Morphic-Theme' with: 'Glamour-Morphic-Theme-TheIntegrator.229';
			package: 'Glamour-Morphic-Widgets' with: 'Glamour-Morphic-Widgets-AliakseiSyrel.205';
			package: 'Glamour-Morphic-Renderer' with: 'Glamour-Morphic-Renderer-JurajKubelka.357';
			package: 'Glamour-Morphic-Pager' with: 'Glamour-Morphic-Pager-AliakseiSyrel.113';
			package: 'Glamour-Tests-Morphic' with: 'Glamour-Tests-Morphic-AndreiChis.138';
			package: 'Glamour-Rubric-Presentations' with: 'Glamour-Rubric-Presentations-JurajKubelka.60';
			package: 'Glamour-Tests-Rubric' with: 'Glamour-Tests-Rubric-AndreiChis.36';
			package: 'Glamour-SpecIntegration' with: 'Glamour-SpecIntegration-TheIntegrator.6'. ].
