public
commentForCurrentUpdate
 ^ 'Issue 5906:	Better comment for Class>>#copy
	http://code.google.com/p/pharo/issues/detail?id=5906
	
Issue 5898:	Fixing version browsing and ring historical behavior
	http://code.google.com/p/pharo/issues/detail?id=5898
	
Issue 5895:	Change History separator in nautilus history
	http://code.google.com/p/pharo/issues/detail?id=5895

Issue 5894:	Mini improvement in MethodWidget API
	http://code.google.com/p/pharo/issues/detail?id=5894
	'