update50373
	"self new update50373"
	self withUpdateLog: '16628 RBBrowseEnvironment doesnt respect the Set Theory
	https://pharo.fogbugz.com/f/cases/16628

16739 Senders and implementors do not work when one parameter is a selector in the form "with:do" (no space)
	https://pharo.fogbugz.com/f/cases/16739

16745 ReflectiveMethod: do not get class from AST
	https://pharo.fogbugz.com/f/cases/16745'.
	self loadTogether: self script50373 merge: false.
	self flushCaches.
