update50131
	"self new update50131"
	self withUpdateLog: '12728 requestImplementorToInline: is missing in NautilusRefactoring
	https://pharo.fogbugz.com/f/cases/12728

15828 NECController must check that its editor morph is not nil before unsubscribing from it
	https://pharo.fogbugz.com/f/cases/15828

15826 Clean up discouraged uses of SourceFiles and friends (10)
	https://pharo.fogbugz.com/f/cases/15826'.
	self loadTogether: self script50131 merge: false.
	self flushCaches.
