update50494
	"self new update50494"
	self withUpdateLog: '17216 Morph>>#removeDropShadow does not remove the shadowOffset
	https://pharo.fogbugz.com/f/cases/17216

17208 Remove rounded corners from MenuModel parent item
	https://pharo.fogbugz.com/f/cases/17208

16920 In TreeModel>>acceptDropBlock: the block receives morphs as arguments
	https://pharo.fogbugz.com/f/cases/16920'.
	self loadTogether: self script50494 merge: false.
	self flushCaches.
