update50100
	"self new update50100"
	self withUpdateLog: '15722 Remove unused method -= in SHParserST80
	https://pharo.fogbugz.com/f/cases/15722

15725 SystemNavigation shouldnt use Smalltalk globals for self environment
	https://pharo.fogbugz.com/f/cases/15725

15721 Reflectivity: add #name reification for Variables
	https://pharo.fogbugz.com/f/cases/15721'.
	self loadTogether: self script50100 merge: false.
	self flushCaches.
