update50481
	"self new update50481"
	self withUpdateLog: '17165 OCBytecodeEncodingError is not used --> remove
	https://pharo.fogbugz.com/f/cases/17165

15508 SelectionMorph send to back
	https://pharo.fogbugz.com/f/cases/15508

14845 Selecting a class and pressing command B+M raises an error
	https://pharo.fogbugz.com/f/cases/14845

15678 Remove ComposableModel>>#instantiateModels:s senders in NewVersionBrowser
	https://pharo.fogbugz.com/f/cases/15678'.
	self loadTogether: self script50481 merge: false.
	self flushCaches.
