update50221
	"self new update50221"
	self withUpdateLog: '16148 Select next method when remove one in Nautilus
	https://pharo.fogbugz.com/f/cases/16148

16146 unify hasComplexVariables vs usesSpecialVariables
	https://pharo.fogbugz.com/f/cases/16146

16141 Use themed help icons when issue 15079 was integrated (for Help-Core)
	https://pharo.fogbugz.com/f/cases/16141

16160 ProfStef context menu broken
	https://pharo.fogbugz.com/f/cases/16160'.
	self loadTogether: self script50221 merge: false.
	self flushCaches.
