update50214
	"self new update50214"
	self withUpdateLog: '16117 Cleaning Nautilus RotatingString and Friends
	https://pharo.fogbugz.com/f/cases/16117

16118 flatCollect:as: does not return the good collection type if the receiver is empty
	https://pharo.fogbugz.com/f/cases/16118

16105 DNU: receiver of "compilationContext" is nil - AST
	https://pharo.fogbugz.com/f/cases/16105'.
	self loadTogether: self script50214 merge: false.
	self flushCaches.
