update50205
	"self new update50205"
	self withUpdateLog: '14986 Additions to tests for MultiByteFileStream
	https://pharo.fogbugz.com/f/cases/14986

16049 support differnt colors for nested parentheses / blocks in SHRBTextStyler
	https://pharo.fogbugz.com/f/cases/16049

16053 less pluggableTextMorph references
	https://pharo.fogbugz.com/f/cases/16053

16086 reflectivity: testAfterSequence
	https://pharo.fogbugz.com/f/cases/16086'.
	self loadTogether: self script50205 merge: false.
	self flushCaches.
