update50419
	"self new update50419"
	self withUpdateLog: '16931 wrong "method class" for trait methods from a trait method changerecord
	https://pharo.fogbugz.com/f/cases/16931

16489 Monticello browser doesnt update others after adding repo 
	https://pharo.fogbugz.com/f/cases/16489

16743 MCStReader cannot read trait definitions
	https://pharo.fogbugz.com/f/cases/16743

16910 Improve Dictionary comment
	https://pharo.fogbugz.com/f/cases/16910'.
	self loadTogether: self script50419 merge: false.
	self flushCaches.
