update50416
	"self new update50416"
	self withUpdateLog: '16896 Update Nautiluss title when we Rename the browed class.
	https://pharo.fogbugz.com/f/cases/16896

16904 Comment for CollapsedMorph
	https://pharo.fogbugz.com/f/cases/16904

16909 Improve Interval comment
	https://pharo.fogbugz.com/f/cases/16909

16907 Can not inspect  doIt methods 
	https://pharo.fogbugz.com/f/cases/16907'.
	self loadTogether: self script50416 merge: false.
	self flushCaches.
