update50166
	"self new update50166"
	self withUpdateLog: '15856 When we cancel the creation of a class we get an error
	https://pharo.fogbugz.com/f/cases/15856

15939 ChangesBrowser missing tests
	https://pharo.fogbugz.com/f/cases/15939

15943 Cleaning LessonView
	https://pharo.fogbugz.com/f/cases/15943

15937 DNU MethodChunk on change browser file in
	https://pharo.fogbugz.com/f/cases/15937'.
	self loadTogether: self script50166 merge: false.
	self flushCaches.
