update50548
	"self new update50548"
	self withUpdateLog: '17474 adapt Athens to UnifiedFFI 0.11 (pointer arity logic)
	https://pharo.fogbugz.com/f/cases/17474

17421 RubTextMethodLink and RubTextClassLink Leaks (TextStyling related)
	https://pharo.fogbugz.com/f/cases/17421

17442 Improve Morph>>#flash
	https://pharo.fogbugz.com/f/cases/17442'.
	self loadTogether: self script50548 merge: false.
	self flushCaches.
