update50255
	"self new update50255"
	self withUpdateLog: '16275 You cant use ctrl + shift + f anymore on the debuggeur 
	https://pharo.fogbugz.com/f/cases/16275

16322 Move navigation arrows close to navigation drop list in Nautilus
	https://pharo.fogbugz.com/f/cases/16322

16323 add the concepts of a first class TemporaryVariable
	https://pharo.fogbugz.com/f/cases/16323

16321 started a RBSmalltalkGlobalsRule
	https://pharo.fogbugz.com/f/cases/16321

16307 Fix adding Slots to anonymous classes
	https://pharo.fogbugz.com/f/cases/16307'.
	self loadTogether: self script50255 merge: false.
	self flushCaches.
