update50661
	"self new update50661"
	self withUpdateLog: '17891 creating of a new method in "no messages" category does not update methods list in Nautilus
	https://pharo.fogbugz.com/f/cases/17891

16309 ThreadSafeTranscript>>examples doesnt work anymore
	https://pharo.fogbugz.com/f/cases/16309

16922 Nautilus: Using class pane menu entry "Add class" can cause problems
	https://pharo.fogbugz.com/f/cases/16922

17878 KM calls to unimplemented methods
	https://pharo.fogbugz.com/f/cases/17878'.
	self loadTogether: self script50661 merge: false.
	self flushCaches.
