update50271
	"self new update50271"
	self withUpdateLog: '16385 Clean a lot of dead code and unused class variables in Nautilus
	https://pharo.fogbugz.com/f/cases/16385

16382 Remove PluggableTextMorph reference in SyntaxErrorDebugger
	https://pharo.fogbugz.com/f/cases/16382

16378 Highlighting code in Komitter
	https://pharo.fogbugz.com/f/cases/16378

16190 UIManager should not depends on Polymorph-Widgets
	https://pharo.fogbugz.com/f/cases/16190'.
	self loadTogether: self script50271 merge: false.
	self flushCaches.
