update50590
	"self new update50590"
	self withUpdateLog: '17116 The same method is duplicated 5 times in the image
	https://pharo.fogbugz.com/f/cases/17116

17623 Failing test on CI: AllocationTest>#testOutOfMemorySignal
	https://pharo.fogbugz.com/f/cases/17623

17643  Evaluating variables while debugging may yield wrong values
	https://pharo.fogbugz.com/f/cases/17643

17639 The example for SpecPreDebugWindow  no longer works
	https://pharo.fogbugz.com/f/cases/17639'.
	self loadTogether: self script50590 merge: false.
	self flushCaches.
