update50191
	"self new update50191"
	self withUpdateLog: '16026 remove RBExplicitVariableParser
	https://pharo.fogbugz.com/f/cases/16026

16024 QualityAssitances uses deprecate method #category
	https://pharo.fogbugz.com/f/cases/16024

16021 Support creation of colors from HSL coordinates
	https://pharo.fogbugz.com/f/cases/16021'.
	self loadTogether: self script50191 merge: false.
	self loadConfiguration: 'QualityAssistant' version: 'v1.1.2'.self flushCaches.
