update50475
	"self new update50475"
	self withUpdateLog: '17143 With QA warning for uninitialised Variables, we can remove it from the Compiler
	https://pharo.fogbugz.com/f/cases/17143

17104 Cleaning Komitter code
	https://pharo.fogbugz.com/f/cases/17104

17038 DebugActionExecuted should be triggered for every debugging action
	https://pharo.fogbugz.com/f/cases/17038

17115 DNU when draging an element of PopupChoiceDialogWindow.
	https://pharo.fogbugz.com/f/cases/17115

17102 two tests in SugsMenuBuilderTest failing
	https://pharo.fogbugz.com/f/cases/17102'.
	self loadTogether: self script50475 merge: false.
	self flushCaches.
