update50675
	"self new update50675"
	self withUpdateLog: '17930 MenuModel>>fromSpec: fails to open a PluggableMenuSpec if it contains a subMenu
	https://pharo.fogbugz.com/f/cases/17930

17932 Natuilus "Class" button no longer shows if theres anything on the class-side
	https://pharo.fogbugz.com/f/cases/17932

17929 Missing parenthesis around condition (testAsCommaStringMore)
	https://pharo.fogbugz.com/f/cases/17929'.
	self loadTogether: self script50675 merge: false.
	self flushCaches.
