update50201
	"self new update50201"
	self withUpdateLog: '15512 Method deprecated but not in Deprecated50 
	https://pharo.fogbugz.com/f/cases/15512

16041 Rubric is not using source code font anymore since update 50192
	https://pharo.fogbugz.com/f/cases/16041

16070 RBPatternBlockNode should implement #isPatternBlockNode and return true
	https://pharo.fogbugz.com/f/cases/16070'.
	self loadTogether: self script50201 merge: false.
	self loadConfiguration: 'Rubric' version: '1.16.4'.self flushCaches.
