update50383
	"self new update50383"
	self withUpdateLog: '16774 support invalidation of more core classes
	https://pharo.fogbugz.com/f/cases/16774

16592 Incorrect position of "Unknown character hint ->"
	https://pharo.fogbugz.com/f/cases/16592

16514 "Create initializer with inst vars" is broken 
	https://pharo.fogbugz.com/f/cases/16514

16769 infinite loop in Integer>>#putOn: if stream contains a ByteArray
	https://pharo.fogbugz.com/f/cases/16769'.
	self loadTogether: self script50383 merge: false.
	self flushCaches.
