update50478
	"self new update50478"
	self withUpdateLog: '17162 add Breakpoint class >> #browseAll
	https://pharo.fogbugz.com/f/cases/17162

17168 #beForSmalltalkCode should enable #withTextSegmentIcons
	https://pharo.fogbugz.com/f/cases/17168

17145 remove watchpoint package
	https://pharo.fogbugz.com/f/cases/17145

17158 submenu does not close on mouse leave / can not open another submenu
	https://pharo.fogbugz.com/f/cases/17158'.
	self loadTogether: self script50478 merge: false.
	self flushCaches.
