update50291
	"self new update50291"
	self withUpdateLog: '16370 retryOnCredentialRequest: introduces a lot of repeated code and dependencies into monticello
	https://pharo.fogbugz.com/f/cases/16370

16248 Remove unused ClassCategoryReader and ClassCommentReader
	https://pharo.fogbugz.com/f/cases/16248

16439 improve #isUsed a little
	https://pharo.fogbugz.com/f/cases/16439'.
	self loadTogether: self script50291 merge: false.
	self flushCaches.
