update50266
	"self new update50266"
	self withUpdateLog: '16119 Monticello doent ask for user credidentials
	https://pharo.fogbugz.com/f/cases/16119

16219 BIConfigurableFormatter>>#needsMethodSignatureOnMultipleLinesFor: uses to:do: instead of with:do:
	https://pharo.fogbugz.com/f/cases/16219

16358 Can not commit three changed method to class TemporaryVariable
	https://pharo.fogbugz.com/f/cases/16358'.
	self loadTogether: self script50266 merge: false.
	self flushCaches.
