update50251
	"self new update50251"
	self withUpdateLog: '16292 Make TreeNode of Komitter user friendly
	https://pharo.fogbugz.com/f/cases/16292

16296 Default group with configurations in Nautilus
	https://pharo.fogbugz.com/f/cases/16296

16297 Add shortcut to open variables menu 
	https://pharo.fogbugz.com/f/cases/16297

16288 Remove parallel diff calculation
	https://pharo.fogbugz.com/f/cases/16288'.
	self loadTogether: self script50251 merge: false.
	self flushCaches.
