update50653
	"self new update50653"
	self withUpdateLog: '17847 Remove #undoMove:redo:owner:bounds:predecessor: 
	https://pharo.fogbugz.com/f/cases/17847

17846 Doit snapshots should be skipped
	https://pharo.fogbugz.com/f/cases/17846

16824 Context>>#copyTo:blocks: broken
	https://pharo.fogbugz.com/f/cases/16824

17840 ChangesBrowser selectAll DNU 
	https://pharo.fogbugz.com/f/cases/17840

17851 Reduce width of DiffJointMorph 
	https://pharo.fogbugz.com/f/cases/17851'.
	self loadTogether: self script50653 merge: false.
	self flushCaches.
