update50677
	"self new update50677"
	self withUpdateLog: '17945 TextEditor setEmphasisHereFromTextForward: broken for empty text
	https://pharo.fogbugz.com/f/cases/17945

17943 It is not possible to write [ in Nautilus on the french keyboard layout
	https://pharo.fogbugz.com/f/cases/17943

17937 Monticello does not fully unload packages
	https://pharo.fogbugz.com/f/cases/17937

17621 Failing test SizeInMemoryTest>>#testSizeInMemoryOfByteObjects
	https://pharo.fogbugz.com/f/cases/17621'.
	self loadTogether: self script50677 merge: false.
	self flushCaches.
