update50292
	"self new update50292"
	self withUpdateLog: '15941 Color>>printHtmlString and Color>>asHTMLColor are similar
	https://pharo.fogbugz.com/f/cases/15941

16416 spec predebug notification window should use text without code highlighting
	https://pharo.fogbugz.com/f/cases/16416

16267 Fasttable isnt visible in athens (in bloc)
	https://pharo.fogbugz.com/f/cases/16267'.
	self loadTogether: self script50292 merge: false.
	self loadConfiguration: 'FastTable' version: '0.7.8'.self flushCaches.
