update50283
	"self new update50283"
	self withUpdateLog: '16391 Switching hierarchy visually removes selection of a protocol
	https://pharo.fogbugz.com/f/cases/16391

16331 MergeDiffMorph - Wrong scrollbars
	https://pharo.fogbugz.com/f/cases/16331

16406 RBkeysDoRule has the same #uniqueIdentifierName as RBEqualNilRule
	https://pharo.fogbugz.com/f/cases/16406'.
	self loadTogether: self script50283 merge: false.
	self flushCaches.
