update50453
	"self new update50453"
	self withUpdateLog: '17049 Morphic-Core cleanup
	https://pharo.fogbugz.com/f/cases/17049

17048 visualization of breakpoints logic on nautilus ui + reset logic to support remove all breakpoints on a method
	https://pharo.fogbugz.com/f/cases/17048

17039 Broken context menu in MessageBrowsers code pane
	https://pharo.fogbugz.com/f/cases/17039'.
	self loadTogether: self script50453 merge: false.
	self flushCaches.
