update50016
	"self new update50016"
	self withUpdateLog: '15421 fix offset in SHRBTextStyler
	https://pharo.fogbugz.com/f/cases/15421

15300 MNU: Association>>adaptToNumber:andSend:
	https://pharo.fogbugz.com/f/cases/15300

15398 Deprecated StartupLoader should present migration instructions
	https://pharo.fogbugz.com/f/cases/15398

15405 Suggestion menu SystemNavigation(Object)>>doesNotUnderstand: #browseClassRefsOf:
	https://pharo.fogbugz.com/f/cases/15405'.
	self loadTogether: self script625 merge: false.
	self flushCaches.
