update50561
	"self new update50561"
	self withUpdateLog: '17513 ThemeIcons>>#downloadFromUrl not working
	https://pharo.fogbugz.com/f/cases/17513

17500 Implement class creation methods for new layouts
	https://pharo.fogbugz.com/f/cases/17500

17491 find selector shows syntax error debugger
	https://pharo.fogbugz.com/f/cases/17491'.
	self loadTogether: self script50561 merge: false.
	
ThemeIcons current url: nil.
	self flushCaches.
