update50452
	"self new update50452"
	self withUpdateLog: '17046 announce link remove + fix DNU when Nautilus has no method selected
	https://pharo.fogbugz.com/f/cases/17046

17032 ExternalBrowser should be able to show class definitions
	https://pharo.fogbugz.com/f/cases/17032

17040 Morph HalosEnabled variable is not use.
	https://pharo.fogbugz.com/f/cases/17040

17043 Use uppercase for breakpoint menu item labels in suggestions
	https://pharo.fogbugz.com/f/cases/17043'.
	self loadTogether: self script50452 merge: false.
	self flushCaches.
