update50663
	"self new update50663"
	self withUpdateLog: '17782 RPackageOrganizer data do not full correspond to the newely generated ones
	https://pharo.fogbugz.com/f/cases/17782

15893 Nautilus refresh not fine enough
	https://pharo.fogbugz.com/f/cases/15893

14528 OSWindow: move tests out of package
	https://pharo.fogbugz.com/f/cases/14528

17893 CompiledMethod>>hasLiteralThorough: does not work properly for GlobalVariables
	https://pharo.fogbugz.com/f/cases/17893'.
	self loadTogether: self script50663 merge: false.
	self flushCaches.
