update50055
	"self new update50055"
	self withUpdateLog: '15572 Clean up OldClassBuilderAdapter more
	https://pharo.fogbugz.com/f/cases/15572

15528 Add TTranscript and DailyNonInteractiveTranscript
	https://pharo.fogbugz.com/f/cases/15528

15569 add optional filter to debugger to filter out Reflectivity related contexts
	https://pharo.fogbugz.com/f/cases/15569'.
	self loadTogether: self script50055 merge: false.
	self flushCaches.
