update50120
	"self new update50120"
	self withUpdateLog: '15789 Progress with reifications
	https://pharo.fogbugz.com/f/cases/15789

7367 Nautilus Colors "not in this package" methods differently on instance/class sides
	https://pharo.fogbugz.com/f/cases/7367

15794 Clean up discouraged uses of SourceFiles and friends (5)
	https://pharo.fogbugz.com/f/cases/15794'.
	self loadTogether: self script50120 merge: false.
	self flushCaches.
