update50236
	"self new update50236"
	self withUpdateLog: '16214 Reput the shortcuts for browsing etc in Monticello
	https://pharo.fogbugz.com/f/cases/16214

16212 ChunkWriteStream doesnt understand many messages...
	https://pharo.fogbugz.com/f/cases/16212

16225 Adding facilities to define repositories to publish in the catalog browser
	https://pharo.fogbugz.com/f/cases/16225

16234 Add a button to load and create a group in Catalog Browser 
	https://pharo.fogbugz.com/f/cases/16234'.
	self loadTogether: self script50236 merge: false.
	self flushCaches.
