update50048
	"self new update50048"
	self withUpdateLog: '15551 debugger does not accept code change
	https://pharo.fogbugz.com/f/cases/15551

15548 core image: remove methods that are equivalent to ones they override 
	https://pharo.fogbugz.com/f/cases/15548

15547 RBFutureDeprecationWarningRule not highlighting the issue
	https://pharo.fogbugz.com/f/cases/15547

15539 JPEGReadWriter class>>understandsImageFormat: result unexpected
	https://pharo.fogbugz.com/f/cases/15539'.
	self loadTogether: self script50048 merge: false.
	self flushCaches.
