update50231
	"self new update50231"
	self withUpdateLog: '16208 System-Support should have a System-Support-Tests
	https://pharo.fogbugz.com/f/cases/16208

16179 Reflectivity: Set Links on Globals
	https://pharo.fogbugz.com/f/cases/16179

16216 Default values in NECPreferences are not initilized right
	https://pharo.fogbugz.com/f/cases/16216'.
	self loadTogether: self script50231 merge: false.
	self flushCaches.
