update50062
	"self new update50062"
	self withUpdateLog: '15594 Clean OldClassBuilderAdapter more...
	https://pharo.fogbugz.com/f/cases/15594

15595 Add special semantic checker when compiling reflective methods
	https://pharo.fogbugz.com/f/cases/15595

15593 Fix SystemDictionary comment about behaviors
	https://pharo.fogbugz.com/f/cases/15593'.
	self loadTogether: self script50062 merge: false.
	self flushCaches.
