update50333
	"self new update50333"
	self withUpdateLog: '16606 remove bubble like ballon tooltip from menus
	https://pharo.fogbugz.com/f/cases/16606

16605 senders/implementors window shows unrelated content
	https://pharo.fogbugz.com/f/cases/16605

16598 Cannot save the contents of the standard workspace to disk
	https://pharo.fogbugz.com/f/cases/16598

16596 #before for Class Variable
	https://pharo.fogbugz.com/f/cases/16596'.
	self loadTogether: self script50333 merge: false.
	self flushCaches.
