update50649
	"self new update50649"
	self withUpdateLog: '17831 [Theme] Move color changes from #installFullTheme 
	https://pharo.fogbugz.com/f/cases/17831

17397 We have a group for Configurations, we should have one for baselines.
	https://pharo.fogbugz.com/f/cases/17397

17779 allow RPackageOrganizer initialization from a list of packages
	https://pharo.fogbugz.com/f/cases/17779'.
	self loadTogether: self script50649 merge: false.
	
Nautilus resetGroups.
	self flushCaches.
