update50483
	"self new update50483"
	self withUpdateLog: '17167 disable NEC completion in method comments
	https://pharo.fogbugz.com/f/cases/17167

17181 Rename layout to classLayout (step 3.5 replace implementation in Behavior)
	https://pharo.fogbugz.com/f/cases/17181

16724 new removal of RubPluggableTextMorph
	https://pharo.fogbugz.com/f/cases/16724

17178 Move checking logic of #handleMouseMove: into #handlesMouseMove: 
	https://pharo.fogbugz.com/f/cases/17178'.
	self loadTogether: self script50483 merge: false.
	self flushCaches.
