update50022
	"self new update50022"
	self withUpdateLog: '15447 Links with MetaContext
	https://pharo.fogbugz.com/f/cases/15447

15436 emitStore: should not send writeToSlot:of:
	https://pharo.fogbugz.com/f/cases/15436

15444 OldClassBuilderAdapter: move checks into SlotClassBuilder (first step)
	https://pharo.fogbugz.com/f/cases/15444'.
	self loadTogether: self script631 merge: false.
	self flushCaches.
