update50472
	"self new update50472"
	self withUpdateLog: '17136 [cleanup] remove unused PackageTreeGroupNodeModel
	https://pharo.fogbugz.com/f/cases/17136

17135 WatchpointTests>>#testTimestamp
	https://pharo.fogbugz.com/f/cases/17135

17106 better MethodDictionary comment
	https://pharo.fogbugz.com/f/cases/17106

17130 Morph+BorderedMorph SystemWindow Protocol cleanup
	https://pharo.fogbugz.com/f/cases/17130

17080 Special Object Array does not hold the right Processor association
	https://pharo.fogbugz.com/f/cases/17080'.
	self loadTogether: self script50472 merge: false.
	
Smalltalk recreateSpecialObjectsArray.
	self flushCaches.
