update50408
	"self new update50408"
	self withUpdateLog: '16850 RingChunkImporter>>#removedMethod:with: calls: addRemovedSelector:
	https://pharo.fogbugz.com/f/cases/16850

15969 move method refactoring does not work anymore
	https://pharo.fogbugz.com/f/cases/15969

16836 Cant remove an instance variable and a trait in one step
	https://pharo.fogbugz.com/f/cases/16836

16876 Improve speed of OrderedDictionary>>#atRandom:
	https://pharo.fogbugz.com/f/cases/16876'.
	self loadTogether: self script50408 merge: false.
	self flushCaches.
