update50395
	"self new update50395"
	self withUpdateLog: '16827  #sourceInterval should work for every RBNode - Yes even RBArrayNode
	https://pharo.fogbugz.com/f/cases/16827

16826 GrafPort font methods should be moved to the package Graphics-Fonts
	https://pharo.fogbugz.com/f/cases/16826

16823 Color>>#fillRectangle:on: should be in Graphics-Canvas
	https://pharo.fogbugz.com/f/cases/16823

16831 unimplemented call in MCFileTreeAbstractReader>>#packageProperties 
	https://pharo.fogbugz.com/f/cases/16831'.
	self loadTogether: self script50395 merge: false.
	self flushCaches.
