update50289
	"self new update50289"
	self withUpdateLog: '16340 ExternalBrowser or "Recover lost changes"  broken
	https://pharo.fogbugz.com/f/cases/16340

16432 add Color>>#asHexString
	https://pharo.fogbugz.com/f/cases/16432

16421 ChunkWriter does not save correctly wideStrings
	https://pharo.fogbugz.com/f/cases/16421

16433 simplify #unreferencedKeys
	https://pharo.fogbugz.com/f/cases/16433'.
	self loadTogether: self script50289 merge: false.
	self flushCaches.
