update50627
	"self new update50627"
	self withUpdateLog: '13376 Wrong TextMorph extent for ButtonMorphs
	https://pharo.fogbugz.com/f/cases/13376

15733 let MessageTally ignore #home and just use #sender to handle block closures correctly
	https://pharo.fogbugz.com/f/cases/15733

15562 rewrite tests that are skipped when old compiler is unloaded
	https://pharo.fogbugz.com/f/cases/15562

17746 adding a Slot to an anonymous class sets name ivar.
	https://pharo.fogbugz.com/f/cases/17746

17739 remove duplicated methods from Traits
	https://pharo.fogbugz.com/f/cases/17739'.
	self loadTogether: self script50627 merge: false.
	self flushCaches.
