update50338
	"self new update50338"
	self withUpdateLog: '15858 review rule RBAbstractClassRule
	https://pharo.fogbugz.com/f/cases/15858

16402 Diff view partly broken (Refactorgin ChangesBrowser)
	https://pharo.fogbugz.com/f/cases/16402

16600 System-Changes should not depend on system-FileRegistry
	https://pharo.fogbugz.com/f/cases/16600'.
	self loadTogether: self script50338 merge: false.
	self flushCaches.
