update50532
	"self new update50532"
	self withUpdateLog: '17314 MNU: PackageTreePackageSelection>>packageName if we try to run code critics on scoped package
	https://pharo.fogbugz.com/f/cases/17314

17407 Smart suggestions shortcut should use Cmd instead of Meta
	https://pharo.fogbugz.com/f/cases/17407

17405 Format shortcut throw DNU in comment pane.
	https://pharo.fogbugz.com/f/cases/17405

17396 "MonticelloRepositoryBrowser example" MNU
	https://pharo.fogbugz.com/f/cases/17396'.
	self loadTogether: self script50532 merge: false.
	self flushCaches.
