update50341
	"self new update50341"
	self withUpdateLog: '16591 #findVariable:ifNone: methods needs to go back to Opal
	https://pharo.fogbugz.com/f/cases/16591

16633 Rename layout to  classLayout (step 1 add accessor)
	https://pharo.fogbugz.com/f/cases/16633

16639 fix non common smalltalk syntax in PointTest
	https://pharo.fogbugz.com/f/cases/16639'.
	self loadTogether: self script50341 merge: false.
	self flushCaches.
