update50600
	"self new update50600"
	self withUpdateLog: '17620 WeakFinalizersTest>>#testNewFinalizationSupported (Cleanup needed)
	https://pharo.fogbugz.com/f/cases/17620

17608 Failing on CI Server: ChunkImportTestCase>>#testImportAClassCategory
	https://pharo.fogbugz.com/f/cases/17608

17640 Batch deletion of methods raise DNU in some cases
	https://pharo.fogbugz.com/f/cases/17640

16756 ZnUnknownHttpVersion(Object)>>doesNotUnderstand: #response
	https://pharo.fogbugz.com/f/cases/16756'.
	self loadTogether: self script50600 merge: false.
	self flushCaches.
