update50349
	"self new update50349"
	self withUpdateLog: '16669 MetaLinks on Slots
	https://pharo.fogbugz.com/f/cases/16669

16670 optionInlineCondition: do not inline condition
	https://pharo.fogbugz.com/f/cases/16670

16668 Variables button throws KeynotFound when a variable is selected
	https://pharo.fogbugz.com/f/cases/16668'.
	self loadTogether: self script50349 merge: false.
	self flushCaches.
