update50665
	"self new update50665"
	self withUpdateLog: '17218 needs to use new spec drag n drop transfer models
	https://pharo.fogbugz.com/f/cases/17218

17823 Critic browser is not dark theme friendly
	https://pharo.fogbugz.com/f/cases/17823

17898 RPackage>>#isDirty speedup
	https://pharo.fogbugz.com/f/cases/17898'.
	self loadTogether: self script50665 merge: false.
	self loadConfiguration: 'Versionner' version: '2.13.10'.self flushCaches.
