update50752
	"self new update50752"
	self withUpdateLog: '18178 Some methods comments in FileReference
	https://pharo.fogbugz.com/f/cases/18178

18174 Delete the second " of the template method break the image
	https://pharo.fogbugz.com/f/cases/18174

18168 Add Tooltip to describe Rubric options
	https://pharo.fogbugz.com/f/cases/18168'.
	self loadTogether: self script50752 merge: false.
	self flushCaches.
