update50391
	"self new update50391"
	self withUpdateLog: '16795 The package Random includes tests
	https://pharo.fogbugz.com/f/cases/16795

16800 ask a SpecWindow for #isDisplayed always returns true
	https://pharo.fogbugz.com/f/cases/16800

16803 Renaming method category with floating editor: size of editing rectangle
	https://pharo.fogbugz.com/f/cases/16803'.
	self loadTogether: self script50391 merge: false.
	self flushCaches.
