update50335
	"self new update50335"
	self withUpdateLog: '16519 Deprecate WeakSubscriptionBuilder>>#on:send:to: and #on:do:
	https://pharo.fogbugz.com/f/cases/16519

16613 add timeout for SimulateMouseSpecification
	https://pharo.fogbugz.com/f/cases/16613

16565 Remove senders of subscribe:send:to: in PragmaCollector
	https://pharo.fogbugz.com/f/cases/16565

16563 Remove senders of Announcer>>#subscribe:send:to: in Morphic-Widgets-Tree
	https://pharo.fogbugz.com/f/cases/16563'.
	self loadTogether: self script50335 merge: false.
	self flushCaches.
