update50723
	"self new update50723"
	self withUpdateLog: '16961 Unable to accept changes in SyntaxErrorDebugger -> DNU: receiver of asSymbol is nil
	https://pharo.fogbugz.com/f/cases/16961

18111 SortHierarchically >> buildHierarchyForClasses: speedup
	https://pharo.fogbugz.com/f/cases/18111

18107 Failing on windows: GlobalIdentifierWithFuel>>#testBackwardCompatibility4 
	https://pharo.fogbugz.com/f/cases/18107'.
	self loadTogether: self script50723 merge: false.
	self flushCaches.
