update50082
	"self new update50082"
	self withUpdateLog: '15666 Class rename does not update references in class-side methods
	https://pharo.fogbugz.com/f/cases/15666

15659 LucidaGrande font should be installed just in Macs
	https://pharo.fogbugz.com/f/cases/15659

15535 break circular reference for keymappings
	https://pharo.fogbugz.com/f/cases/15535'.
	self loadTogether: self script50082 merge: false.
	self flushCaches.
