update50116
	"self new update50116"
	self withUpdateLog: '15754 New Code Critic for unary "accessing" methods without explicit returns
	https://pharo.fogbugz.com/f/cases/15754

15739 lastKeystroke broken
	https://pharo.fogbugz.com/f/cases/15739

15146 Spec TabManagerModel>>selectedTab: aTab manipulates with Morphic tab
	https://pharo.fogbugz.com/f/cases/15146

15781 Fix TraitMethodDescriptionTest>>testArgumentNames
	https://pharo.fogbugz.com/f/cases/15781'.
	self loadTogether: self script50116 merge: false.
	self flushCaches.
