update50344
	"self new update50344"
	self withUpdateLog: '16647 Nautilus Variable Menu Improvement
	https://pharo.fogbugz.com/f/cases/16647

16648 ThemeSettings protocol cleanup
	https://pharo.fogbugz.com/f/cases/16648

16649 Links of Globals and Class Vars: implement all reifications + extend for Globals
	https://pharo.fogbugz.com/f/cases/16649'.
	self loadTogether: self script50344 merge: false.
	self flushCaches.
