update50246
	"self new update50246"
	self withUpdateLog: '16239 hasReportTableSlip is not packaged well and more
	https://pharo.fogbugz.com/f/cases/16239

16264 update ring-core-kernel dependencies
	https://pharo.fogbugz.com/f/cases/16264

16272 Reflectivity: start of code gen for Globals
	https://pharo.fogbugz.com/f/cases/16272

16192 Cut Text-Core dependencies
	https://pharo.fogbugz.com/f/cases/16192'.
	self loadTogether: self script50246 merge: false.
	self flushCaches.
