update50431
	"self new update50431"
	self withUpdateLog: '16971 fix: support primitive methods wit arguments
	https://pharo.fogbugz.com/f/cases/16971

16918 Cant configure a tree to auto refresh when a node is folded and then unfolded
	https://pharo.fogbugz.com/f/cases/16918

16908 wrong source node for pc in mustBeBooleanInMagic
	https://pharo.fogbugz.com/f/cases/16908

16970 Cleaning Graphics-Shapes categorisation
	https://pharo.fogbugz.com/f/cases/16970'.
	self loadTogether: self script50431 merge: false.
	self flushCaches.
