update50290
	"self new update50290"
	self withUpdateLog: '16435 add Context>>#sourceNodeExecuted
	https://pharo.fogbugz.com/f/cases/16435

16434 can not inspect block methods (RBUnpackagedRule)
	https://pharo.fogbugz.com/f/cases/16434

16426 new OSWindow integration to clean up wrong merge
	https://pharo.fogbugz.com/f/cases/16426'.
	self loadTogether: self script50290 merge: false.
	self loadConfiguration: 'OSWindow' version: '1.2.6'.self flushCaches.
