update50480
	"self new update50480"
	self withUpdateLog: '17086 remove setting for #emptyCommentWarning
	https://pharo.fogbugz.com/f/cases/17086

17148 Seeing changes and then merge them generates merge conflicts
	https://pharo.fogbugz.com/f/cases/17148

17169 fix refresh for "Implementors of"
	https://pharo.fogbugz.com/f/cases/17169

15242 SettingDeclaration>> inputWidget should not override  widget model
	https://pharo.fogbugz.com/f/cases/15242'.
	self loadTogether: self script50480 merge: false.
	self flushCaches.
