update50060
	"self new update50060"
	self withUpdateLog: '10120 StrikeFont default writeAsStrike2On: strikefont.bin fails - DNU
	https://pharo.fogbugz.com/f/cases/10120

15587 clean up SugAbstractContext>>#tools
	https://pharo.fogbugz.com/f/cases/15587

15591 Generate Hooks for links with conditions that get arguments passed in
	https://pharo.fogbugz.com/f/cases/15591'.
	self loadTogether: self script50060 merge: false.
	self flushCaches.
