update50380
	"self new update50380"
	self withUpdateLog: '16752 problems with new search function in FastTable
	https://pharo.fogbugz.com/f/cases/16752

16753 Invalidate ProtoObject
	https://pharo.fogbugz.com/f/cases/16753

15713 CommandLineUIManager>>#merge:informing: is not doing anything
	https://pharo.fogbugz.com/f/cases/15713'.
	self loadTogether: self script50380 merge: false.
	self flushCaches.
