update50248
	"self new update50248"
	self withUpdateLog: '14789 Nautilus can not browse anonymous classes
	https://pharo.fogbugz.com/f/cases/14789

16302 Move variable assignment outside of blocks and Rewrite ifTrue:ifFalse: using min:/max: in Rectangle>>#intersect:ifNone:
	https://pharo.fogbugz.com/f/cases/16302

16261 Monticello window is ridiculously small when opened from the world menu
	https://pharo.fogbugz.com/f/cases/16261

16291 Remove scary weel of the Komitter
	https://pharo.fogbugz.com/f/cases/16291'.
	self loadTogether: self script50248 merge: false.
	self flushCaches.
