update50125
	"self new update50125"
	self withUpdateLog: '15812 MessageNotUnderstood: RGMethodDefinition>>ast (Suggestions expects it)
	https://pharo.fogbugz.com/f/cases/15812

15791 Cleanup Script actions for methods
	https://pharo.fogbugz.com/f/cases/15791

15557 New PackageManifests should be classes, not instances
	https://pharo.fogbugz.com/f/cases/15557'.
	self loadTogether: self script50125 merge: false.
	self flushCaches.
