update50410
	"self new update50410"
	self withUpdateLog: '16883 Highlight in Senders of... throws a MNU if the search term was found in a class comment
	https://pharo.fogbugz.com/f/cases/16883

16818 Renaming a Class triggers debugger 
	https://pharo.fogbugz.com/f/cases/16818

16886 Quick access to startup preferences folder
	https://pharo.fogbugz.com/f/cases/16886'.
	self loadTogether: self script50410 merge: false.
	self flushCaches.
