update50401
	"self new update50401"
	self withUpdateLog: '16840 Each browser has its own classifier
	https://pharo.fogbugz.com/f/cases/16840

16819 dropping a ".changes" file on the world does not open changes browser
	https://pharo.fogbugz.com/f/cases/16819

16837 Refactor AboutDialogWindow
	https://pharo.fogbugz.com/f/cases/16837'.
	self loadTogether: self script50401 merge: false.
	self flushCaches.
