update50350
	"self new update50350"
	self withUpdateLog: '16674 Navigate from Variables to AST Node accessing that variable
	https://pharo.fogbugz.com/f/cases/16674

16677 #after on Globals and Slots
	https://pharo.fogbugz.com/f/cases/16677

16676 Desktop Logo hidden behind Background image
	https://pharo.fogbugz.com/f/cases/16676

16660 improve #isUsed for Behaviours
	https://pharo.fogbugz.com/f/cases/16660

'.
	self loadTogether: self script50350 merge: false.
	self flushCaches.
self cleanRepositories.
