update50634
	"self new update50634"
	self withUpdateLog: '16972 Access to variable catch too much announcements
	https://pharo.fogbugz.com/f/cases/16972

17787 QualityAssistant v2.5.0
	https://pharo.fogbugz.com/f/cases/17787

17781 you can not use printIt Pharo Tutorials
	https://pharo.fogbugz.com/f/cases/17781

17784 move asMCMethodDefinition and related messages to Monticello package
	https://pharo.fogbugz.com/f/cases/17784'.
	self loadTogether: self script50634 merge: false.
	self loadConfiguration: 'QualityAssistant' version: 'v2.5.0'.self flushCaches.
