update50152
	"self new update50152"
	self withUpdateLog: '7008 Shared Pools to be treated like dictionaries still necessary?
	https://pharo.fogbugz.com/f/cases/7008

15886 Find class dialog from a scope nautilus window shows all classes
	https://pharo.fogbugz.com/f/cases/15886

15889 do not call asOrderedCollection on compiled methods
	https://pharo.fogbugz.com/f/cases/15889

15892 Cleanups: clean annotation handling + rename HookGenerator2
	https://pharo.fogbugz.com/f/cases/15892'.
	self loadTogether: self script50152 merge: false.
	self flushCaches.
