update50386
	"self new update50386"
	self withUpdateLog: '16789 RBUnaryAccessingMethodWithoutReturnRule refers to #nodes instead of #statements
	https://pharo.fogbugz.com/f/cases/16789

16758 Unify SystemWindow announcing with Morph announcing 
	https://pharo.fogbugz.com/f/cases/16758

16653 Add an architectural rule for the bootstrap layer
	https://pharo.fogbugz.com/f/cases/16653'.
	self loadTogether: self script50386 merge: false.
	self flushCaches.
