update50141
	"self new update50141"
	self withUpdateLog: '13416 Problem with Refactoring : temporary to instvar
	https://pharo.fogbugz.com/f/cases/13416

15760 ToggleMenuItemShortcut do not draw on athens
	https://pharo.fogbugz.com/f/cases/15760

15854 template proposed to dynamically create class (on the fly)
	https://pharo.fogbugz.com/f/cases/15854

15852 Reflectivity: #ensure: wrapping #after
	https://pharo.fogbugz.com/f/cases/15852'.
	self loadTogether: self script50141 merge: false.
	self loadConfiguration: 'Athens' version: '3.6'.self flushCaches.
