update50393
	"self new update50393"
	self withUpdateLog: '16816 Storing System Settings produces error when preference directory does not exist
	https://pharo.fogbugz.com/f/cases/16816

16809 Sort the variables from each class in the variables-menu alphabetically
	https://pharo.fogbugz.com/f/cases/16809

16810 Floating editor size too large for Nautilus package pane 
	https://pharo.fogbugz.com/f/cases/16810'.
	self loadTogether: self script50393 merge: false.
	self flushCaches.
