update50464
	"self new update50464"
	self withUpdateLog: '17095 small code critique cleanup in NautilusCommon
	https://pharo.fogbugz.com/f/cases/17095

17094 Small code critique cleanup in Morphic-Widgets-Tabs
	https://pharo.fogbugz.com/f/cases/17094

17090 Opening debugger API cleanup. Part3
	https://pharo.fogbugz.com/f/cases/17090

16936 Desktop Background Image changes aspect ratio whenever the Pharo World window does 
	https://pharo.fogbugz.com/f/cases/16936'.
	self loadTogether: self script50464 merge: false.
	self flushCaches.
