update50047
	"self new update50047"
	self withUpdateLog: '15362 No "underline" or "stroke out" emphasis on FT fonts
	https://pharo.fogbugz.com/f/cases/15362

15538 Versionner commit tool does not handle correctly username and password request
	https://pharo.fogbugz.com/f/cases/15538

6769 Debugger does not warn the user when a trait method is overridden
	https://pharo.fogbugz.com/f/cases/6769'.
	self loadTogether: self script50047 merge: false.
	self loadConfiguration: 'Versionner' version: '2.13.3'.self flushCaches.
