update50334
	"self new update50334"
	self withUpdateLog: '16597 DNU RBParseErrorNode>>statements: when  | is placed before a .
	https://pharo.fogbugz.com/f/cases/16597

16599 Compression should not depend on Graphics-Display Object (leftover)
	https://pharo.fogbugz.com/f/cases/16599

16610 test: block body vs block
	https://pharo.fogbugz.com/f/cases/16610'.
	self loadTogether: self script50334 merge: false.
	self flushCaches.
