update50397
	"self new update50397"
	self withUpdateLog: '16834 implement Nautilus class>>emptyCommentWarning:
	https://pharo.fogbugz.com/f/cases/16834

16437 World Contents Menu should have a maximum string length for its elements
	https://pharo.fogbugz.com/f/cases/16437

16830 fix known locales initialization
	https://pharo.fogbugz.com/f/cases/16830

16825 make standalone Gofer-UI package
	https://pharo.fogbugz.com/f/cases/16825'.
	self loadTogether: self script50397 merge: false.
	self flushCaches.
