update50146
	"self new update50146"
	self withUpdateLog: '15874 Reflectvity: small refactoring
	https://pharo.fogbugz.com/f/cases/15874

15873 Clean new class builder: #copyTraitCompositionFromExistingClass not needed
	https://pharo.fogbugz.com/f/cases/15873

15870 TestRunner: packages is shadowed
	https://pharo.fogbugz.com/f/cases/15870'.
	self loadTogether: self script50146 merge: false.
	self flushCaches.
