update50042
	"self new update50042"
	self withUpdateLog: '15510 Missed some part of the original 15199 
	https://pharo.fogbugz.com/f/cases/15510

15518 association is misspelled in OrderedDictionary>>printElementsOn:
	https://pharo.fogbugz.com/f/cases/15518

15509 SelectionMorph>>extent: broken
	https://pharo.fogbugz.com/f/cases/15509

15474 Some Color method comments refere to Color>>showColors:
	https://pharo.fogbugz.com/f/cases/15474'.
	self loadTogether: self script651 merge: false.
	self flushCaches.
