update50626
	"self new update50626"
	self withUpdateLog: '17392 FreeType numCharMaps nil causes Array>>basicNew: to fail
	https://pharo.fogbugz.com/f/cases/17392

17740 RBSelfSentNotImplementedRule needs to ignore Traits methods
	https://pharo.fogbugz.com/f/cases/17740

17215 Proposed fix for OCLiteralVariable>>emitValue:
	https://pharo.fogbugz.com/f/cases/17215

17132 better comment for flushcache
	https://pharo.fogbugz.com/f/cases/17132'.
	self loadTogether: self script50626 merge: false.
	self flushCaches.
