update50541
	"self new update50541"
	self withUpdateLog: '17404 ExternalBrowser can not show meta class definition
	https://pharo.fogbugz.com/f/cases/17404

17443 RubTextAreaExamples>>#show:while: should not use #displayWorldSafely
	https://pharo.fogbugz.com/f/cases/17443

17457 Change Growl setting name to PopupNotifier
	https://pharo.fogbugz.com/f/cases/17457'.
	self loadTogether: self script50541 merge: false.
	self flushCaches.
