update50682
	"self new update50682"
	self withUpdateLog: '17015 Failing test: SetTest>>#testAllSetsAreHealthy
	https://pharo.fogbugz.com/f/cases/17015

17979  (MessageDialogWindow new text: Hello) open should work
	https://pharo.fogbugz.com/f/cases/17979

17897 Slot method used by Nautilus but not implemented
	https://pharo.fogbugz.com/f/cases/17897'.
	self loadTogether: self script50682 merge: false.
	self flushCaches.
