update50123
	"self new update50123"
	self withUpdateLog: '15806 Clean up NautilusRefactoring 
	https://pharo.fogbugz.com/f/cases/15806

15805 support #newValue on assignmentNode + cleanups
	https://pharo.fogbugz.com/f/cases/15805

15807 Revisiting RBUnpackagedCodeRule
	https://pharo.fogbugz.com/f/cases/15807

15801 MorphTreeMorph improvement
	https://pharo.fogbugz.com/f/cases/15801'.
	self loadTogether: self script50123 merge: false.
	self flushCaches.
