update50347
	"self new update50347"
	self withUpdateLog: '16654 test for  #optionOneShot and accessors for pre-defined options
	https://pharo.fogbugz.com/f/cases/16654

16662 SlotClassBuilderError --> tClassBuilderError
	https://pharo.fogbugz.com/f/cases/16662

16658 Reflectivity: crash on Morph Invalidate
	https://pharo.fogbugz.com/f/cases/16658'.
	self loadTogether: self script50347 merge: false.
	self flushCaches.
