update50399
	"self new update50399"
	self withUpdateLog: '16844 TextConverter seems not to be using poolDictionary EventSensorConstants
	https://pharo.fogbugz.com/f/cases/16844

16848 unimplemented call in MetacelloToolbox>>#baselineNamed:
	https://pharo.fogbugz.com/f/cases/16848

16838 Missing return caret in RBVariableReferencedOnceRule>>basicCheck
	https://pharo.fogbugz.com/f/cases/16838

16851 SMTPClient class>>#deliver:usingServer: should be in the package Network-Mail
	https://pharo.fogbugz.com/f/cases/16851'.
	self loadTogether: self script50399 merge: false.
	self flushCaches.
