update50348
	"self new update50348"
	self withUpdateLog: '16663 Minor tweaks to the Nautilus variable menu
	https://pharo.fogbugz.com/f/cases/16663

16667 do not inline meta link: #optionInlineMetaObject
	https://pharo.fogbugz.com/f/cases/16667

14618 Add a comment describing RBFileBlocksRule
	https://pharo.fogbugz.com/f/cases/14618'.
	self loadTogether: self script50348 merge: false.
	self flushCaches.
