update50073
	"self new update50073"
	self withUpdateLog: '15626 SHRBStyle dnu for incomplete block nodes
	https://pharo.fogbugz.com/f/cases/15626

15628 Remove ComposableModel>>#instantiateModels:s senders in Keymapping-Tools-Spec
	https://pharo.fogbugz.com/f/cases/15628

15621 show complete menu modifiers
	https://pharo.fogbugz.com/f/cases/15621'.
	self loadTogether: self script50073 merge: false.
	self flushCaches.
