update50296
	"self new update50296"
	self withUpdateLog: '16448 #instead for Array
	https://pharo.fogbugz.com/f/cases/16448

16444 ASt-Core should not have a BlueInk rpackage tag
	https://pharo.fogbugz.com/f/cases/16444

16438 Deprecate Color>>printHtmlString and Color>>asHTMLColor
	https://pharo.fogbugz.com/f/cases/16438

14765 Missing calls of "super release" in #release methods
	https://pharo.fogbugz.com/f/cases/14765'.
	self loadTogether: self script50296 merge: false.
	self flushCaches.
