update50427
	"self new update50427"
	self withUpdateLog: '16958 Fix name analysis RF 
	https://pharo.fogbugz.com/f/cases/16958

16954 Smalltalk globals cleaning in ProtoObject and Tools
	https://pharo.fogbugz.com/f/cases/16954

16956 DNU from Syntaxhighligher tries to parse method in VersionBrowser
	https://pharo.fogbugz.com/f/cases/16956'.
	self loadTogether: self script50427 merge: false.
	self flushCaches.
