update50538
	"self new update50538"
	self withUpdateLog: '17444 SVColorSelectorMorph should not use (World displayWorldSafely)
	https://pharo.fogbugz.com/f/cases/17444

17408 The generic stack debugger defines double meaning for some keybindings when editing code
	https://pharo.fogbugz.com/f/cases/17408

17335 We should add a #ffiSizeOf: 
	https://pharo.fogbugz.com/f/cases/17335'.
	self loadTogether: self script50538 merge: false.
	self loadConfiguration: 'UnifiedFFI' version: '0.10.1'.self flushCaches.
