update50009
	"self new update50009"
	self withUpdateLog: '15372 forward port pharaoh: 15339 Monticello with spotter extension methods throws MNU errors when browsing packages in repos that don
	https://pharo.fogbugz.com/f/cases/15372

15380 Failing test: ClassTest.testClassRespectsPolymorphismWithTrait
	https://pharo.fogbugz.com/f/cases/15380'.
	self loadTogether: self script618 merge: false.
	self flushCaches.
