update50367
	"self new update50367"
	self withUpdateLog: '16713 Update FastTable (See description for more info)
	https://pharo.fogbugz.com/f/cases/16713

16568 STCommandLineHandler class >>#isResponsibleFor: and >>#activate are not consistent
	https://pharo.fogbugz.com/f/cases/16568

16692 Simplification of Author>>#checkAndSetFullNameWith:
	https://pharo.fogbugz.com/f/cases/16692'.
	self loadTogether: self script50367 merge: false.
	self loadConfiguration: 'FastTable' version: '0.7.9'.self flushCaches.
