update50672
	"self new update50672"
	self withUpdateLog: '16775 Class Button is in the wrong state sometimes
	https://pharo.fogbugz.com/f/cases/16775

17871 Slots need to be notified when they changed
	https://pharo.fogbugz.com/f/cases/17871

16373 Methods called but not implemented in SUnit
	https://pharo.fogbugz.com/f/cases/16373'.
	self loadTogether: self script50672 merge: false.
	self flushCaches.
