update50163
	"self new update50163"
	self withUpdateLog: '15907 add beForCode for all tools using specs TextModel 
	https://pharo.fogbugz.com/f/cases/15907

15921 Make SystemReporter use Rubric
	https://pharo.fogbugz.com/f/cases/15921

15934 test: Coverage per method, see #testCoverageMethod
	https://pharo.fogbugz.com/f/cases/15934'.
	self loadTogether: self script50163 merge: false.
	self flushCaches.
