update50068
	"self new update50068"
	self withUpdateLog: '13829 TextMorphForEditorView should be packaged in Moprhic-Widgets-Pluggable
	https://pharo.fogbugz.com/f/cases/13829

2906 Analyze #adaptToNumber:andSend:
	https://pharo.fogbugz.com/f/cases/2906

14040 FillStyle>>fillRectangle: aRectangle on: aCanvas should be packaged in Balloon
	https://pharo.fogbugz.com/f/cases/14040

15613 Display most use tools shortcuts on World menu.
	https://pharo.fogbugz.com/f/cases/15613

15135 Object extensions related to explore/inspect should be repackaged into their own independent package
	https://pharo.fogbugz.com/f/cases/15135'.
	self loadTogether: self script50068 merge: false.
	self flushCaches.
