update50462
	"self new update50462"
	self withUpdateLog: '17081 remove PackageTreeNautilusUI
	https://pharo.fogbugz.com/f/cases/17081

17085 QualityAssistant v2.1
	https://pharo.fogbugz.com/f/cases/17085

17078 Dont transform method argument access extra tempVars for to:do: transformations
	https://pharo.fogbugz.com/f/cases/17078'.
	self loadTogether: self script50462 merge: false.
	self loadConfiguration: 'QualityAssistant' version: 'v2.1.0'.self flushCaches.
