update50594
	"self new update50594"
	self withUpdateLog: '17649 Rename method in class side does not change class side methods in other classes
	https://pharo.fogbugz.com/f/cases/17649

17648 WeakSet >>#asArray returns wrong result after some objects lifetime is finished
	https://pharo.fogbugz.com/f/cases/17648

17647 Collection asArray "array variable is shadowed"
	https://pharo.fogbugz.com/f/cases/17647

17628 OSEnvironment current "an UnixEnvironment" [Windows]
	https://pharo.fogbugz.com/f/cases/17628'.
	self loadTogether: self script50594 merge: false.
	self flushCaches.
