update50353
	"self new update50353"
	self withUpdateLog: '16691 MouseFocus and triggering modal dialogs from mouse event dispatcher
	https://pharo.fogbugz.com/f/cases/16691

16690 Spec WidgetBuilt is send with an Adapter but it should be a widget (Morph)
	https://pharo.fogbugz.com/f/cases/16690

16068 Debugger is losing the source code changes on method context change
	https://pharo.fogbugz.com/f/cases/16068

16688 Coverage Demo with Reflectivity
	https://pharo.fogbugz.com/f/cases/16688

16490 MorphSlot
	https://pharo.fogbugz.com/f/cases/16490'.
	self loadTogether: self script50353 merge: false.
	self flushCaches.
