update50467
	"self new update50467"
	self withUpdateLog: '17103 support for watchpoint with optionWeakAfter metalink
	https://pharo.fogbugz.com/f/cases/17103

17107 Strange effect after opening the Debugger: sometimes two UI processes
	https://pharo.fogbugz.com/f/cases/17107

17105 Have a minimal UI for seeing watchpoints
	https://pharo.fogbugz.com/f/cases/17105

17101 clean AnnotationRequest
	https://pharo.fogbugz.com/f/cases/17101

17100 DropEvent should not check the type in #sentTo:
	https://pharo.fogbugz.com/f/cases/17100'.
	self loadTogether: self script50467 merge: false.
	self flushCaches.
