update50439
	"self new update50439"
	self withUpdateLog: '16992 deprecate methodDictAddSelectorSilently:withMethod:
	https://pharo.fogbugz.com/f/cases/16992

16952 Change class template creation
	https://pharo.fogbugz.com/f/cases/16952

16975 versionner (Object>>#name) 
	https://pharo.fogbugz.com/f/cases/16975'.
	self loadTogether: self script50439 merge: false.
	self loadConfiguration: 'Versionner' version: '2.13.7'.self flushCaches.
