update50374
	"self new update50374"
	self withUpdateLog: '16741 remove addModelMenuItemsTo:forMorph:hand:
	https://pharo.fogbugz.com/f/cases/16741

16729 Removing PluggableTextField from FT
	https://pharo.fogbugz.com/f/cases/16729

16744 ReflectiveMethod: make sure to not use DNU forwarding on invalidate
	https://pharo.fogbugz.com/f/cases/16744'.
	self loadTogether: self script50374 merge: false.
	self flushCaches.
