update50050
	"self new update50050"
	self withUpdateLog: '12358 Even if ---all--- can not be removed, all the methods can ...
	https://pharo.fogbugz.com/f/cases/12358

15550 TBehavior>>referencedClasses is wrong
	https://pharo.fogbugz.com/f/cases/15550

15500 SpecTreeNodeModel(Object)>>doesNotUnderstand: #content
	https://pharo.fogbugz.com/f/cases/15500'.
	self loadTogether: self script50050 merge: false.
	self flushCaches.
