update50264
	"self new update50264"
	self withUpdateLog: '16352 some RubExamples dont work anymore
	https://pharo.fogbugz.com/f/cases/16352

16285 Files should not depend on Graphics-Primitives
	https://pharo.fogbugz.com/f/cases/16285

16353 TemporyVariable: pointer to method and block startpc
	https://pharo.fogbugz.com/f/cases/16353'.
	self loadTogether: self script50264 merge: false.
	self loadConfiguration: 'Rubric' version: '1.18.3'.self flushCaches.
