update50394
	"self new update50394"
	self withUpdateLog: '16786 Code formatter moves comments to wrong place
	https://pharo.fogbugz.com/f/cases/16786

16815 DNU RBAndEnvironment>>packageNames while producing html report bootstrap architecture rule
	https://pharo.fogbugz.com/f/cases/16815

16817 like 16798 #sourceInterval should work for every RBNode - RBLiteralNode too
	https://pharo.fogbugz.com/f/cases/16817

16711 FileDialogWindow should fail silently on DirectoryDoesNotExist: when clicking on Junctions (Windows)
	https://pharo.fogbugz.com/f/cases/16711

16807 SystemWindow refactoring (Events, activation ++)
	https://pharo.fogbugz.com/f/cases/16807'.
	self loadTogether: self script50394 merge: false.
	self flushCaches.
