Object subclass: #CCompilationContext
	instanceVariableNames: 'astTranslatorClass bytecodeGeneratorClass category class compiledMethodTrailer encoderClass environment failBlock interactive logged noPattern options parserClass requestor forSyntaxHighlighting semanticAnalyzerClass astTransformPlugins usesFullBlockClosure'
	classVariableNames: 'BytecodeBackend UsesFullBlockClosure'
	poolDictionaries: ''
	category: 'OpalCompiler-Core-FrontEnd'