Object subclass: #CCompilationContext
	instanceVariableNames: 'astTranslatorClass bytecodeGeneratorClass category class compiledMethodTrailer encoderClass environment failBlock interactive logged noPattern options parserClass requestor forSyntaxHighlighting semanticAnalyzerClass astTransformPlugins'
	classVariableNames: 'BytecodeBackend WarningAllowed'
	poolDictionaries: ''
	category: 'OpalCompiler-Core-FrontEnd'