update60167
	"self new update60167"
	self withUpdateLog: '18858 #testUndeclared fails: missing ivars in RadioButtonModel
	https://pharo.fogbugz.com/f/cases/18858

18821 format code creates invalid pragma statement
	https://pharo.fogbugz.com/f/cases/18821

18843 #digitLength is implemented in SmallInteger and in BigInteger but not in Integer
	https://pharo.fogbugz.com/f/cases/18843'.
	self loadTogether: self script60167 merge: false.
	self flushCaches.
