update60241
	"self new update60241"
	self withUpdateLog: '19121 DNU in VersionBrowser when switching from "side by side" to "source"
	https://pharo.fogbugz.com/f/cases/19121

19143 in Code Critique browser: DNU #setTextModelForTransformationRule: 
	https://pharo.fogbugz.com/f/cases/19143

18914 Improve MethodClassifier classification based on selector parts
	https://pharo.fogbugz.com/f/cases/18914

19141 Optimize String>>#substrings:
	https://pharo.fogbugz.com/f/cases/19141'.
	self loadTogether: self script60241 merge: false.
	self flushCaches.
