update60109
	"self new update60109"
	self withUpdateLog: '18574 SingleCodeCriticResultList>>#criticsOf: raises warning name depreciated
	https://pharo.fogbugz.com/f/cases/18574

18568 RecursionStopper
	https://pharo.fogbugz.com/f/cases/18568

18582 Nautilus rename method protocol triggers a Object>>#name deprecation warning
	https://pharo.fogbugz.com/f/cases/18582'.
	self loadTogether: self script60109 merge: false.
	self flushCaches.
