update60185
	"self new update60185"
	self withUpdateLog: '18944 misspackaged Intege r>> readFrom: radix:
	https://pharo.fogbugz.com/f/cases/18944

18945 do not require a Text in MockSourceEditor
	https://pharo.fogbugz.com/f/cases/18945

18937 RBRefactoryTestDataApp and RBSmallintTestObject #fileBlocks sends undefined #asFilename
	https://pharo.fogbugz.com/f/cases/18937'.
	self loadTogether: self script60185 merge: false.
	self flushCaches.
