update60020
	"self new update60020"
	self withUpdateLog: '18248 TextAction>>rubActOnClick:for:in:editor: missing
	https://pharo.fogbugz.com/f/cases/18248

18270 add #themeChanged method for GLMTabLabelBrick
	https://pharo.fogbugz.com/f/cases/18270

18266 OCClassScope should ask class directly to find variable 
	https://pharo.fogbugz.com/f/cases/18266'.
	self loadTogether: self script60020 merge: false.
	self flushCaches.
