update60209
	"self new update60209"
	self withUpdateLog: '19065 Symbol>>#asMethodPreamble isBroken
	https://pharo.fogbugz.com/f/cases/19065

17879 Wrong example or code in Generator class comment
	https://pharo.fogbugz.com/f/cases/17879

19063 Factory for RBModel classes
	https://pharo.fogbugz.com/f/cases/19063

19047 fix vmstats report for spur
	https://pharo.fogbugz.com/f/cases/19047

19056 Trait Polymorphism tests fail again
	https://pharo.fogbugz.com/f/cases/19056'.
	self loadTogether: self script60209 merge: false.
	self flushCaches.
