update60121
	"self new update60121"
	self withUpdateLog: '18629 use debug icon for debug submenu
	https://pharo.fogbugz.com/f/cases/18629

18137 Network test failing only on MAC on CI: UDPSocketEchoTest.testEcho
	https://pharo.fogbugz.com/f/cases/18137

18626 Guard calls to isGlobal from Rules
	https://pharo.fogbugz.com/f/cases/18626

18631 Add critiques to message browser
	https://pharo.fogbugz.com/f/cases/18631'.
	self loadTogether: self script60121 merge: false.
	self flushCaches.
