update60198
	"self new update60198"
	self withUpdateLog: '18859 Loading a package break word selection on Windows
	https://pharo.fogbugz.com/f/cases/18859

18930 Regression: Time to show big methods is too high
	https://pharo.fogbugz.com/f/cases/18930

19020 add preUnload message to Manifest
	https://pharo.fogbugz.com/f/cases/19020

19022 asClass rules
	https://pharo.fogbugz.com/f/cases/19022

18827 Mirror primitives should be easy to use
	https://pharo.fogbugz.com/f/cases/18827'.
	self loadTogether: self script60198 merge: false.
	self flushCaches.
