update60271
	"self new update60271"
	self withUpdateLog: '19252 Implement Model specific methods from Object into Model
	https://pharo.fogbugz.com/f/cases/19252

19016 Are  UIManager>>chooseFileMatching: and friends really useful?
	https://pharo.fogbugz.com/f/cases/19016

19254 Improve RubLipsumWithSegmentsExample>>#loremIpsum
	https://pharo.fogbugz.com/f/cases/19254

19249 Simple Shell Command Eval was gone in Pharo 6
	https://pharo.fogbugz.com/f/cases/19249'.
	self loadTogether: self script60271 merge: false.
	self loadConfiguration: 'UnifiedFFI' version: '0.24'.self flushCaches.
