update60363
	"self new update60363"
	self withUpdateLog: '19618 MCVersion>>printOn: using deprecated Object>>name
	https://pharo.fogbugz.com/f/cases/19618

19393 Nested blocks at methods start not show correct temps sometimes
	https://pharo.fogbugz.com/f/cases/19393

19617 Revert 18232
	https://pharo.fogbugz.com/f/cases/19617

19380 UFFI structure raises author request when generates field accessors
	https://pharo.fogbugz.com/f/cases/19380'.
	self loadTogether: self script60363 merge: false.
	self flushCaches.
