update60285
	"self new update60285"
	self withUpdateLog: '18146 VirtualMachine>>loadModule: always fails
	https://pharo.fogbugz.com/f/cases/18146

19267 Can not accept "Code Rewrite" template for regex refactorings
	https://pharo.fogbugz.com/f/cases/19267

19317 MethodClassifier order should be changed
	https://pharo.fogbugz.com/f/cases/19317'.
	self loadTogether: self script60285 merge: false.
	self flushCaches.
