update60157
	"self new update60157"
	self withUpdateLog: '18740 selectAll of TextInputFieldModel dont react like its super class TextModel
	https://pharo.fogbugz.com/f/cases/18740

18824 Fuel packages lost some integrated stuff
	https://pharo.fogbugz.com/f/cases/18824

18750 Improve the abstract TestCase for widgets
	https://pharo.fogbugz.com/f/cases/18750'.
	self loadTogether: self script60157 merge: false.
	self loadConfiguration: 'Fuel' version: '2.1.7'.self flushCaches.
