update60180
	"self new update60180"
	self withUpdateLog: '18920 optional work with sources in TBehavior>>#addTraitSelector:withMethod:
	https://pharo.fogbugz.com/f/cases/18920

18927 Komitter throws up if it has committed everything
	https://pharo.fogbugz.com/f/cases/18927

18919 GridTests should not be part of CollectionsTests
	https://pharo.fogbugz.com/f/cases/18919

18924 Small demo: type feedback using meta links
	https://pharo.fogbugz.com/f/cases/18924

18913 simplify #allReferencesTo:
	https://pharo.fogbugz.com/f/cases/18913'.
	self loadTogether: self script60180 merge: false.
	self flushCaches.
