update60114
	"self new update60114"
	self withUpdateLog: '18614 add a "Debug" menu for halt / breakpoints
	https://pharo.fogbugz.com/f/cases/18614

18599 use sendsAnySelectorOf: in RBBadMessageRule
	https://pharo.fogbugz.com/f/cases/18599

18611 Fix warnings that refer to inexistant methods (maxExternalObjects & maxExternalObjectsSilently:)
	https://pharo.fogbugz.com/f/cases/18611

18305 MCWorkingCopyBrowser class>>#order would benefit to have a comment
	https://pharo.fogbugz.com/f/cases/18305

18605 add DoOnlyOnceIconStyler
	https://pharo.fogbugz.com/f/cases/18605'.
	self loadTogether: self script60114 merge: false.
	self flushCaches.
