update60170
	"self new update60170"
	self withUpdateLog: '18816 Failing test: ChangesBrowserTest.testInitializeWidgets
	https://pharo.fogbugz.com/f/cases/18816

18846 <script:> and <script> pragmas do not always work 
	https://pharo.fogbugz.com/f/cases/18846

18782 Add DateAndTime class>>readFrom:defaultOffset:
	https://pharo.fogbugz.com/f/cases/18782

18870 Delivery preparation hook for announcement
	https://pharo.fogbugz.com/f/cases/18870'.
	self loadTogether: self script60170 merge: false.
	self flushCaches.
