update60295
	"self new update60295"
	self withUpdateLog: '19335 Syntax highlighting do not work on methods with primitives that uses "ec"
	https://pharo.fogbugz.com/f/cases/19335

19340 Can not step over methods with meta links
	https://pharo.fogbugz.com/f/cases/19340

19343 Spec is now dependent on FastTable
	https://pharo.fogbugz.com/f/cases/19343

19351 ClassTagAnnouncement is needed to describe operations with class tags
	https://pharo.fogbugz.com/f/cases/19351'.
	self loadTogether: self script60295 merge: false.
	self flushCaches.
