update60265
	"self new update60265"
	self withUpdateLog: '19220 MNU in Find and Replace on accepting empty input
	https://pharo.fogbugz.com/f/cases/19220

17194 users of PluggableTextEditorMorph should use Rubric
	https://pharo.fogbugz.com/f/cases/17194

18904 Opened Find And Replace dialog from fasttables search is uncloseable
	https://pharo.fogbugz.com/f/cases/18904'.
	self loadTogether: self script60265 merge: false.
	self flushCaches.
