update60140
	"self new update60140"
	self withUpdateLog: '18696 some cleanup for OCBytecodeDecompilerTest for new Bytecode set
	https://pharo.fogbugz.com/f/cases/18696

18680 Forward port 18676 Endless loop parsing e-mail addresses containing an ampersand
	https://pharo.fogbugz.com/f/cases/18680

18694 deprecate #getSource
	https://pharo.fogbugz.com/f/cases/18694'.
	self loadTogether: self script60140 merge: false.
	self flushCaches.
