update60029
	"self new update60029"
	self withUpdateLog: '18309 Typo in RBSmalltalkGlobalsRule
	https://pharo.fogbugz.com/f/cases/18309

18308 "Replaces detect:ifNone: by anySatisfy:" misleading rationale
	https://pharo.fogbugz.com/f/cases/18308

18247 deprecation warning on #isManifest for metaclasses
	https://pharo.fogbugz.com/f/cases/18247

18079 Boolean>>xor
	https://pharo.fogbugz.com/f/cases/18079'.
	self loadTogether: self script60029 merge: false.
	self flushCaches.
