update60197
	"self new update60197"
	self withUpdateLog: '19019 Inexactitude in Dictionary class>> newFromPairs: comment
	https://pharo.fogbugz.com/f/cases/19019

18950 CritiqueBrowser: Compiler error when accepting a method with argument
	https://pharo.fogbugz.com/f/cases/18950

18992 asClass in font related package
	https://pharo.fogbugz.com/f/cases/18992

18988 FreeTypeFontProvider should calculate correctly the directories where to look for fonts.
	https://pharo.fogbugz.com/f/cases/18988'.
	self loadTogether: self script60197 merge: false.
	self flushCaches.
