update60290
	"self new update60290"
	self withUpdateLog: '19281 We should improve the class comment of RBComment
	https://pharo.fogbugz.com/f/cases/19281

19330 Finish renames of tab related morphs
	https://pharo.fogbugz.com/f/cases/19330

19334 When a protocol is selected the added method should not be automatically sorted.
	https://pharo.fogbugz.com/f/cases/19334

19337 missing stroke-out for deprecated methods
	https://pharo.fogbugz.com/f/cases/19337'.
	self loadTogether: self script60290 merge: false.
	self flushCaches.
