update60243
	"self new update60243"
	self withUpdateLog: '18032 mightBeASquare should be implemented in LargePositiveInteger
	https://pharo.fogbugz.com/f/cases/18032

19154 Move to RPackage logic to retrieve actual class tags
	https://pharo.fogbugz.com/f/cases/19154

19100 Senders of with Full closures
	https://pharo.fogbugz.com/f/cases/19100'.
	self loadTogether: self script60243 merge: false.
	self flushCaches.
