update60225
	"self new update60225"
	self withUpdateLog: '19093 WeakSet anyOne is not work correctly when only nil there
	https://pharo.fogbugz.com/f/cases/19093

19089 About dialog: add a space to Pharo6.0...
	https://pharo.fogbugz.com/f/cases/19089

17881 loading package which add extension method to trait from external package makes loadable package dirty
	https://pharo.fogbugz.com/f/cases/17881

19077 extend ClassDescription>>printSubclassesOn:level: to have a filter
	https://pharo.fogbugz.com/f/cases/19077'.
	self loadTogether: self script60225 merge: false.
	self flushCaches.
