update60296
	"self new update60296"
	self withUpdateLog: '19350 SystemAnnouncer cannot be reset in minimal/bootstrapped Pharo
	https://pharo.fogbugz.com/f/cases/19350

19328 Undeclared ShortRunArray again
	https://pharo.fogbugz.com/f/cases/19328

19326 failing test: testClassRespectsPolymorphismWithTrait
	https://pharo.fogbugz.com/f/cases/19326'.
	self loadTogether: self script60296 merge: false.
	self flushCaches.
