update60110
	"self new update60110"
	self withUpdateLog: '18586 add String>>#trimmLineSpaces
	https://pharo.fogbugz.com/f/cases/18586

18591 fix call to #name in asEpiceaRingDefinition
	https://pharo.fogbugz.com/f/cases/18591

18583 For experiments: Option to compile with syntax errors
	https://pharo.fogbugz.com/f/cases/18583

18585 deprecated:transformWith: should to Transcript output
	https://pharo.fogbugz.com/f/cases/18585'.
	self loadTogether: self script60110 merge: false.
	self flushCaches.
