update60283
	"self new update60283"
	self withUpdateLog: '19299 Missing border after dragging out of a window group
	https://pharo.fogbugz.com/f/cases/19299

18286 Provide notice of missing package description in CatalogBrowser
	https://pharo.fogbugz.com/f/cases/18286

19309 RBSourceRegexRefactoring calls not existing method on RBClass
	https://pharo.fogbugz.com/f/cases/19309'.
	self loadTogether: self script60283 merge: false.
	self flushCaches.
