update60253
	"self new update60253"
	self withUpdateLog: '19166 Why Object>>#-> doesnt use Association class>>#key:value:?
	https://pharo.fogbugz.com/f/cases/19166

19157 The method Pragma>>#selector called from MetacelloToolBox>>#modifySymbolicVersionMethodFor:symbolicVersionSpecsDo: has been depr
	https://pharo.fogbugz.com/f/cases/19157

19175 LongTestCase cleanup
	https://pharo.fogbugz.com/f/cases/19175

19177 SharedQueue does not implement #atEnd and #contents
	https://pharo.fogbugz.com/f/cases/19177'.
	self loadTogether: self script60253 merge: false.
	self flushCaches.
