update60048
	"self new update60048"
	self withUpdateLog: '18354 Improve MorphTreeColumnButton #themeChanged
	https://pharo.fogbugz.com/f/cases/18354

17967 IRTranslator not using compilation when created by IRMethod #generate.
	https://pharo.fogbugz.com/f/cases/17967

18317 Dictionary>>#at:ifPresent:ifAbsentPut: does not exist, could we add it ?
	https://pharo.fogbugz.com/f/cases/18317'.
	self loadTogether: self script60048 merge: false.
	self flushCaches.
