update60179
	"self new update60179"
	self withUpdateLog: '18910 MNU: OrderedCollection>>parent: when trying to rewrite a tree with RBParseTreeRewriter
	https://pharo.fogbugz.com/f/cases/18910

18911 unify property API of CompiledMethod with all the others (Class, AST...)
	https://pharo.fogbugz.com/f/cases/18911

18912 update comment Deprecation
	https://pharo.fogbugz.com/f/cases/18912'.
	self loadTogether: self script60179 merge: false.
	self flushCaches.
