update60191
	"self new update60191"
	self withUpdateLog: '18967 wrong title for "add trait" dialog
	https://pharo.fogbugz.com/f/cases/18967

18954 ClassTest>>#testMethodsReferencingClass and testMethodsReferencingClasses should not use external packages
	https://pharo.fogbugz.com/f/cases/18954

18975 copy sort --> sorted
	https://pharo.fogbugz.com/f/cases/18975

18976 SmallDictionary>>#associationAt:ifPresent: is not implemented
	https://pharo.fogbugz.com/f/cases/18976'.
	self loadTogether: self script60191 merge: false.
	self flushCaches.
