update60107
	"self new update60107"
	self withUpdateLog: '18557 DialogWindow: close window should act as "Cancel"
	https://pharo.fogbugz.com/f/cases/18557

18565 sendersOf autoselect selects wrong interval
	https://pharo.fogbugz.com/f/cases/18565

18254 Strange results of Integer>>#asBytesDescription
	https://pharo.fogbugz.com/f/cases/18254'.
	self loadTogether: self script60107 merge: false.
	self flushCaches.
