update60430
	"self new update60430"
	self withUpdateLog: '19806 RGTraitDefinitionTest>>#testAddingMethods often fails on the bootstrapped image
	https://pharo.fogbugz.com/f/cases/19806

19804 Fix text coloring for droplist items when chaning theme 
	https://pharo.fogbugz.com/f/cases/19804

19356 QANautilusPluginMorph progressbarMorph do not handle theme changing
	https://pharo.fogbugz.com/f/cases/19356

19355 Literal ByteArray misses syntax highlighting 
	https://pharo.fogbugz.com/f/cases/19355'.
	self loadTogether: self script60430 merge: false.
	self flushCaches.
