update60172
	"self new update60172"
	self withUpdateLog: '18878 MNU ReINvocationSequenceRule isArchitecturalRule
	https://pharo.fogbugz.com/f/cases/18878

18886 parsing an unfinished block with invalid expressions in its body should not create only a single parse error node
	https://pharo.fogbugz.com/f/cases/18886

18883 SystemReporter calls deprecated #name on MCWorkingCopy
	https://pharo.fogbugz.com/f/cases/18883'.
	self loadTogether: self script60172 merge: false.
	self flushCaches.
