update60147
	"self new update60147"
	self withUpdateLog: '18736 STCommandLineHandler>>installSourceFile:
	https://pharo.fogbugz.com/f/cases/18736

18727 MessageBrowser Suggestions shortcut ignores selection
	https://pharo.fogbugz.com/f/cases/18727

18718 usage of deprecated Pragma>>#selector in the kernel
	https://pharo.fogbugz.com/f/cases/18718'.
	self loadTogether: self script60147 merge: false.
	self flushCaches.
