update60158
	"self new update60158"
	self withUpdateLog: '18766 Change TabModelTest and TabManagerTest to use the abstract class
	https://pharo.fogbugz.com/f/cases/18766

18833 Error on TreeModels drag&drop
	https://pharo.fogbugz.com/f/cases/18833

18830 RBPatternParser should respect RBErrorNode when parsing pattern blocks
	https://pharo.fogbugz.com/f/cases/18830

18826 failing tests testMethodsReferencingClass on bootstrapped image
	https://pharo.fogbugz.com/f/cases/18826'.
	self loadTogether: self script60158 merge: false.
	self flushCaches.
