update60364
	"self new update60364"
	self withUpdateLog: '19277 FastTable not support deselection while command click is used on multiple selection
	https://pharo.fogbugz.com/f/cases/19277

18880 Autogenerating accessors should be less naive
	https://pharo.fogbugz.com/f/cases/18880

19371 Doc: Main announcement classes could point to the tutorial in help browser
	https://pharo.fogbugz.com/f/cases/19371

19543 FTPluggableIconListMorphAdaptor does not update selection after filtering
	https://pharo.fogbugz.com/f/cases/19543'.
	self loadTogether: self script60364 merge: false.
	self flushCaches.
