update60156
	"self new update60156"
	self withUpdateLog: '18822 RBScanner>>#scanPatternVariable shouldnt continue parsing on error
	https://pharo.fogbugz.com/f/cases/18822

18771 Add a manifest for critics
	https://pharo.fogbugz.com/f/cases/18771

18743 Create an abstract class to remove code duplication between CheckboxModel and RadioButtonModel
	https://pharo.fogbugz.com/f/cases/18743

18803 Cleanup of Spec-Polywidget
	https://pharo.fogbugz.com/f/cases/18803'.
	self loadTogether: self script60156 merge: false.
	self flushCaches.
