update60047
	"self new update60047"
	self withUpdateLog: '18356 add protocol dialog does not list existing protocols from class side
	https://pharo.fogbugz.com/f/cases/18356

18365 Move Polymorph-Widgets extension PSMCMergeMorph>>#initialColorInSystemWindow:
	https://pharo.fogbugz.com/f/cases/18365

18360 Move TestReviver to SUnit-UI package
	https://pharo.fogbugz.com/f/cases/18360'.
	self loadTogether: self script60047 merge: false.
	self flushCaches.
