update60187
	"self new update60187"
	self withUpdateLog: '18953 remove Regex dependency from SplitJoinTest>>#testSplitJoinBoundaryCases
	https://pharo.fogbugz.com/f/cases/18953

18916 simplify asSlotCollection for bootstrap
	https://pharo.fogbugz.com/f/cases/18916

18938 Remove RBClassInstVarNotInitializedRule, it is a bad rule
	https://pharo.fogbugz.com/f/cases/18938'.
	self loadTogether: self script60187 merge: false.
	self flushCaches.
