update60159
	"self new update60159"
	self withUpdateLog: '18844 Move String>>#join: to correct protocol
	https://pharo.fogbugz.com/f/cases/18844

18838 ScrollSyncExample seems dont really work
	https://pharo.fogbugz.com/f/cases/18838

18769 Add test for Spec-Core-Widgets
	https://pharo.fogbugz.com/f/cases/18769

18841 Margin improvements
	https://pharo.fogbugz.com/f/cases/18841'.
	self loadTogether: self script60159 merge: false.
	self flushCaches.
