update60175
	"self new update60175"
	self withUpdateLog: '18891 MethodFinderTest>>#testGreaterThanANumber is dependent on order
	https://pharo.fogbugz.com/f/cases/18891

18889 CriticsBrowser "BlockCannotReturn"
	https://pharo.fogbugz.com/f/cases/18889

18896 add support for ignored fields in structures
	https://pharo.fogbugz.com/f/cases/18896

18898 Sista Encoder update for release.
	https://pharo.fogbugz.com/f/cases/18898'.
	self loadTogether: self script60175 merge: false.
	self loadConfiguration: 'UnifiedFFI' version: '0.23'.self flushCaches.
