update60036
	"self new update60036"
	self withUpdateLog: '17928 multiple "bug" categories in critics browser
	https://pharo.fogbugz.com/f/cases/17928

18234 Menus is spelt incorrectly in the setting browser
	https://pharo.fogbugz.com/f/cases/18234

18295 Object>>#confirm:onCancel: should be deprecated and users should use UIManager
	https://pharo.fogbugz.com/f/cases/18295

18202 AbstractNautilusUI>>addIconStyle should use allSubclassesDo
	https://pharo.fogbugz.com/f/cases/18202

18231 Define a color for secondary text in Theme
	https://pharo.fogbugz.com/f/cases/18231'.
	self loadTogether: self script60036 merge: false.
	self flushCaches.
