update60227
	"self new update60227"
	self withUpdateLog: '16877 another endless debugger loop 
	https://pharo.fogbugz.com/f/cases/16877

19097 Move to instance side refactoring of class method in the sender list is mispelled
	https://pharo.fogbugz.com/f/cases/19097

19098 FuelOutStackDebugAction uses incorrect debugger API
	https://pharo.fogbugz.com/f/cases/19098'.
	self loadTogether: self script60227 merge: false.
	self flushCaches.
