update60300
	"self new update60300"
	self withUpdateLog: '19360 Deprecated #selector call in MetacelloVersionConstructor>>#verifyVersionImportPragmas:definedIn:
	https://pharo.fogbugz.com/f/cases/19360

19352 Conflict on package renaming if tag exists
	https://pharo.fogbugz.com/f/cases/19352

19362 Make OSWindow as optional and unloadable
	https://pharo.fogbugz.com/f/cases/19362'.
	self loadTogether: self script60300 merge: false.
	self flushCaches.
