update60132
	"self new update60132"
	self withUpdateLog: '18670 Move the transformation code from #deprecated:transformWith: to Deprecation class
	https://pharo.fogbugz.com/f/cases/18670

18643 make "enable inspect haltOnce" work (Debug menu)
	https://pharo.fogbugz.com/f/cases/18643

18666 Introduce Pragma>>#methodSelector
	https://pharo.fogbugz.com/f/cases/18666'.
	self loadTogether: self script60132 merge: false.
	self flushCaches.
