EXAMPLE
	"At the moment these guys match up with the code in the ProfStef toolbox tutorial"
	
	self example1. "create baseline version 1.0-baseline"
	self example2. "open version 1.0 for development"
	self example3. "update package specs and description in version 1.0"
	self example4. "release versionn 1.0"
	self example5. "open version 1.1 for development"
	self example6. "add new baseline version 1.1 with #pharo section, update version 1.1 dev method"
	self example7. "release version 1.1 on pharo only"
