tearDownPackageList
  ^ #('GoferFoo' 'GoferBar' 'GoferFaux' 'GoferBeau' 'MetacelloTestConfigurationOfFoo')
    ,
      #('GeauxFoo' 'GeauxBar' 'GeauxFaux' 'GeauxBeau' 'MetacelloTestConfigurationOfFum' 'MetacelloTestConfigurationOfFoo' 'MetacelloTestConfigurationOfFeaux' 'MetacelloTestConfigurationOfProjectFie' 'MetacelloTestConfigurationOfProjectFoe' 'MetacelloTestConfigurationOfProjectFee' 'MetacelloTestConfigurationOfFan')