commentForCurrentUpdate
 ^ '13898 RBBlockNode>>#equalTo:withMapping: uses #to:do: instead of #with:do: (Coding Idiom Violation)
	https://pharo.fogbugz.com/f/cases/13898

13901 move DoubleLinkedListTests, LRUCacheTests and TTLCacheTests from Tests
	https://pharo.fogbugz.com/f/cases/13901

13896 RBBlockNode>>#= uses #to:do: instead of #with:do: (Coding Idiom Violation)
	https://pharo.fogbugz.com/f/cases/13896

13900 move TextDiffBuilderTest to ToolsTest
	https://pharo.fogbugz.com/f/cases/13900

13892 Example methods should be runnable in Nautilus
	https://pharo.fogbugz.com/f/cases/13892

'