ScrollPane subclass: #NewList
	instanceVariableNames: 'listCache listSize isInitialized isMultipleSelection selectedIndex selectedIndexes renderer headerHeight headerTitle clickOnHeader lastKeystrokeTime lastKeystrokes secondSelection displayListCache deSelectOnReclick runningProcesses selectionWithKeys drawColor selectedItem selectedItems unselectOnChange iconCache iconMaxSize enabled allowToSelect'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Morphic-Widgets-NewList'