initialize
"
self initialize
"
	PangoAlignment := PangoEllipsizeMode :=  PangoWrapMode := PangoGravity := PangoDirection := gboolean := #int.  
	PangoLayout := #AthensPangoLayout.
	PangoFontDescription := #AthensPangoFontDescription. 
	PangoTabArray := #AthensPangoTabs.
	".

	PangoFontMap := #NBPangoFontMap.
	PangoLanguage := #NBPangoLanguage.
	PangoCairoFontMap := #NBPangoCairoFontMap.
	PangoContext := #AthensPangoContext.
	PangoLayoutIter := #AthensPangoCairoParagraphIterator.
	"
	
	PangoLayoutLine := #AthensPangoLayoutLine.
	
	 