GLMLoggedObject subclass: #GLMPresentation
	instanceVariableNames: 'pane title titleIcon transformation actions condition implicitNotNil dynamicActionsBlock color customValidation shouldValidate acceptsSelection parentPrototype registeredAnnouncers updateActions selectionActions selectionDynamicActionsBlock implicitAllNil rawSelectionTransmissions statusPane sourceLink initializationBlock cachedDisplayedValue labelActionBlock portChangeActions'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Glamour-Core'