step11
"Step 11: Some important aspects of transforms:


  * the transformation matrix is not accessible for direct manipulation,
	instead you can only modify the current transformation, by using different manipulation methods 

  * remember that the order of transformation is important, e.g. translate then scale is not the same than
	scale then translate, even if you using very same values.

  * all transformations are conform to AthensTransform protocol. (we're not covering full protocol in this tutorial)
"

