basicTypesString
	^ Lesson
title: 'Basic types: Strings' 
lesson: 
'"A String is a collection of characters. Use single quotes to create a String object. Print these expressions:"

''PharoTutorial''.

''PharoTutorial'' size.

''abc'' asUppercase.

''Hello World'' reverse. 

"You can access each character using at: message"

''PharoTutorial'' at: 1.

"String concatenation uses the comma operator:"

''PharoTutorial'', '' is cool''.

PharoTutorial next.'