initialization
initialize3
	" self initialize "
	
	LPHANDLE := 'HANDLE*'.
	LPINT := 'INT*'.
	LPLONG := 'LONG*'.
	
	LPVOID := 'void*'.
	LPWORD := 'WORD*'.
	LRESULT := 'LONG_PTR'.
	PBOOL := 'BOOL*'.
	PBOOLEAN := 'BOOLEAN*'.
	PBYTE := 'BYTE*'.
	PCHAR := 'CHAR*'.
	PDWORD := 'DWORD*'.
	PDWORDLONG := 'DWORDLONG*'.
	PDWORD32 := 'DWORD32*'.
	PDWORD64 := 'PDWORD64*'.
	PFLOAT := 'FLOAT*'.
	PHANDLE :='HANDLE*'.
	PHKEY := 'HKEY*'.
	PINT := 'INT*'.
	PINT32 := 'INT32*'.
	PINT64 := 'INT64*'.
	PLCID := 'PDWORD'.
	PLONG := 'LONG*'.
	PLONGLONG := 'LONGLONG*'.
	PLONG32 := 'LONG32*'.
	PLONG64 := 'LONG64*'.
	PSHORT := 'SHORT*'.
	PTBYTE := 'TBYTE*'.
	PTCHAR := 'TCHAR*'.
	PUCHAR := 'UCHAR*'.
	PUINT := 'UINT*'.
	PUINT32 := 'UINT32*'.
	PUINT64 := 'UINT64*'.
	PULONG := 'ULONG*'.
	PULONGLONG := 'ULONGLONG*'.
	PULONG32 := 'ULONG32*'.
	PULONG64 := 'ULONG64*'.
	PUSHORT := 'USHORT*'.
	PVOID := 'void*'.
	PWCHAR := 'WCHAR*'.
	PWORD := 'WORD*'.
	SHORT := 'short'.
	TBYTE := 'TCHAR'.
	UCHAR := #uchar.
	UINT := #uint.
	UINT32 := #uint.
	UINT64 := #uint64.
	ULONG := #ulong.
	ULONGLONG := #ulonglong.
	ULONG32 := #uint.
	ULONG64 := #uint64.
	USHORT := #ushort.
	USN := #LONGLONG.
	VOID := #void.
	WCHAR := #ushort.
	WORD := #ushort.
	WPARAM := #'UINT_PTR'.
	
	
	
	
	
