ComposableModel subclass: #IceGitHubCreatePullRequestModel
	instanceVariableNames: 'repository titleLabel titlePanel headLabel headForkList headBranchList baseLabel baseForkList baseBranchList bodyLabel bodyPanel addButton acceptBlock availableRemotes availableBranchNames baseRemote gitRepositoryInfo credentials baseBranches headRemote'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Iceberg-Plugin-GitHub-View'