Object subclass: #Nautilus
	instanceVariableNames: 'announcer browsedEnvironment browsingHistory plugins selectedCategory selectedClass selectedGroup selectedMethod selectedPackage showCategories showComment sortHierarchically showInstance showHierarchy ui uiClass'
	classVariableNames: 'CommentPosition HistoryMaxSize OpenOnGroups PluginClasses RecentClasses ShowAnnotationPane ShowDebugMenus ShowGroupsOnTop SortHierarchically SwitchClassesAndPackages WarningLimit'
	poolDictionaries: ''
	category: 'Nautilus'