Object subclass: #Nautilus
	instanceVariableNames: 'announcer browsedEnvironment browsingHistory plugins selectedCategory selectedClass selectedGroup selectedMethod selectedPackage showCategories showComment showGroups sortHierarchically showInstance showPackages ui uiClass'
	classVariableNames: 'CommentPosition HistoryMaxSize OpenOnGroups PluginClasses RecentClasses ShowAnnotationPane ShowDebugMenus SortHierarchically SwitchClassesAndPackages WarningLimit'
	poolDictionaries: ''
	category: 'Nautilus'