GLMFormatedPresentation subclass: #GLMListingPresentation
	instanceVariableNames: 'searchBlock filterBlock amountToShowBlock allowsMultipleSelection allowsDeselection tagsStyle helpMessage sortBlock textBackgroundColor dropOnItemBlock allowDropOnItemBlock allowItemDragBlock transformDraggedItemBlock allowExplicitSelectionChange'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Glamour-Presentations'