initialize
	"Initialization code for NewListAdapter"

	super initialize.

	doubleClickSelector := nil asReactiveVariable.
	dragItemSelector := nil asReactiveVariable.
	dropItemSelector := nil asReactiveVariable.
	getDisplaySelector := nil asReactiveVariable.
	getHeaderTitleSelector := nil asReactiveVariable.
	getMenuSelector := nil asReactiveVariable.
	getIndexSelector := nil asReactiveVariable.
	getItemAtIndexSelector := nil asReactiveVariable.
	getItemsSelector := nil asReactiveVariable.
	getListSizeSelector := nil asReactiveVariable.
	keyStrokeSelector := nil asReactiveVariable.
	lastKeystrokeTime := nil asReactiveVariable.
	lastKeystrokes := nil asReactiveVariable.
	model := nil asReactiveVariable.
	list := nil asReactiveVariable.
	setIndexSelector := nil asReactiveVariable.
	wantsDropSelector := nil asReactiveVariable.
	getMenuTitleSelector := nil asReactiveVariable.
	getIconSelector := nil asReactiveVariable.
	getIconMaxSizeSelector := nil asReactiveVariable.
	getIndexesSelector := nil asReactiveVariable.
	separatorSelector := nil asReactiveVariable