getText

	^ '
" an example to show that comments are not counted " 

asdasf
a
s

d

f

as d            kfj.
ha,sdkjhfaksdjhfakjsdhfakjsh.
df.kajhsdf.kajhsdf.kjahsd.fkj.
ahs.dkja.sdkfjha.sdkfjha.skdjfh.kasjdhf.kasjd


hf.aksjdhfakjsdhfwuelriuweliuqywerliquyerliqwuyerlqiwuyerliq
								wuyerliqwuyerlqiuweyrlqiwueyrlqwieuyrlqwiueyrlqwieuyrlqiweuyrlqwiuerylqiwueyrlqiwueyrlqiwueyrlqwiuerylqiwueyrlqiweuyrlqwieuyrlqwiueyrlqweiuyrlqwieuryqlwiehfgh
								
								
							
						((ENTER RANDOM CHARACTERS NOW))'