AlignmentMorph subclass: #PluggableButtonMorph
	instanceVariableNames: 'model label icon getIconSelector getStateSelector actionSelector getLabelSelector getMenuSelector shortcutCharacter askBeforeChanging triggerOnMouseDown offColor onColor feedbackColor showSelectionFeedback allButtons arguments argumentsProvider argumentsSelector gradientLook enabled actionBlock getColorSelector getEnabledSelector lastColor labelMorph iconMorph iconPosition'
	classVariableNames: 'UseGradientLook'
	poolDictionaries: ''
	category: 'Morphic-Widgets-Basic'