AlignmentMorph subclass: #PluggableButtonMorph
	instanceVariableNames: 'model label icon getIconSelector getStateSelector actionSelector font getLabelSelector getMenuSelector shortcutCharacter askBeforeChanging triggerOnMouseDown offColor onColor feedbackColor showSelectionFeedback allButtons arguments argumentsProvider argumentsSelector gradientLook enabled actionBlock getColorSelector getEnabledSelector getFontSelector lastColor labelMorph iconMorph iconPosition'
	classVariableNames: 'UseGradientLook'
	poolDictionaries: ''
	category: 'Morphic-Widgets-Basic-Buttons'