AbstractWidgetModel subclass: #TextModel
	instanceVariableNames: 'aboutToStyleHolder behaviorHolder textHolder actionToPerformHolder readSelectionHolder actionPerformedHolder isCodeCompletionAllowedHolder doItContext doItReceiver hasUnacceptedEdits selection scrollValue menuHolder autoAccept wantsVisualFeedback askBeforeDiscardingEdits'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Spec-Core-Widgets'