update40052
	"self new update40052"
	self withUpdateLog: '13369 Move NautilusRefactoring-Refactorings to Refactorings package
	https://pharo.fogbugz.com/f/cases/13369

13430 CodeRewritingRule can be folded in its superclass
	https://pharo.fogbugz.com/f/cases/13430
	
13374 Move row and Stack Layout close to their superclass
	https://pharo.fogbugz.com/f/cases/13374

13373 Polymorph Pluggable class should be investigated and move to Morphic-Widgets-Pluggable
	https://pharo.fogbugz.com/f/cases/13373'.
	self loadTogether: self script52 merge: false.
	self flushCaches.
