update40525
	"self new update40525"
	self withUpdateLog: '14997 Lazy MCVersionInfo to reduce MC memory use
	https://pharo.fogbugz.com/f/cases/14997

15021 LinkedList>>#collect:thenSelect: is slow
	https://pharo.fogbugz.com/f/cases/15021

15022 ZdcSecureSocketStream trouble reading response with no content-length and connection close
	https://pharo.fogbugz.com/f/cases/15022

15008 Regression: ZnClient HTTPS request through HTTP proxy failing
	https://pharo.fogbugz.com/f/cases/15008'.
	self loadTogether: self script525 merge: false.
	self flushCaches.
