update40314
	"self new update40314"
	self withUpdateLog: '14269 Komitter: Improve layout for long repo names
	https://pharo.fogbugz.com/f/cases/14269

14242 Installing a method is slow
	https://pharo.fogbugz.com/f/cases/14242

14257 Replace Announcer>>#on:send:to:s senders in NativeBoost-Core
	https://pharo.fogbugz.com/f/cases/14257'.
	self loadTogether: self script314 merge: false.
	self flushCaches.
