update40263
	"self new update40263"
	self withUpdateLog: '13742 PluggablePanelMorph looks empty and is only used once in the system
	https://pharo.fogbugz.com/f/cases/13742

14094 Deprecate a few unused String methods
	https://pharo.fogbugz.com/f/cases/14094

13337 Moving a class to a package does not work anymore
	https://pharo.fogbugz.com/f/cases/13337

13331 moving a group of methods class side raises an error
	https://pharo.fogbugz.com/f/cases/13331

11475 Optimize FuelTests >> #tearDownTraits
	https://pharo.fogbugz.com/f/cases/11475'.
	self loadTogether: self script263 merge: false.
	self flushCaches.
