update40521
	"self new update40521"
	self withUpdateLog: '14420 What to do with Polymorph-Geometry
	https://pharo.fogbugz.com/f/cases/14420

14950 Spec help added to the Help Browser
	https://pharo.fogbugz.com/f/cases/14950

15013 enable recompile on run:with:in:
	https://pharo.fogbugz.com/f/cases/15013

15015 GradientFillStyle color selection broken
	https://pharo.fogbugz.com/f/cases/15015'.
	self loadTogether: self script521 merge: false.
	self flushCaches.
