update40277
	"self new update40277"
	self withUpdateLog: '14082 Remove very old repositories in ScriptLoader
	https://pharo.fogbugz.com/f/cases/14082

14138 Nautilus Refactoring 9: rename "showPackages"
	https://pharo.fogbugz.com/f/cases/14138

14136 Replace senders of Announcer>>#on:send:to in Versionner-Spec-Browser
	https://pharo.fogbugz.com/f/cases/14136'.
	self loadTogether: self script277 merge: false.
	self flushCaches.
