update40292
	"self new update40292"
	self withUpdateLog: '14196 Do not use workspace as an editor
	https://pharo.fogbugz.com/f/cases/14196

14086 RBSmalllintChecker is not applying rules in class-side
	https://pharo.fogbugz.com/f/cases/14086

14133 UIManager should not overuse the workspace for editing
	https://pharo.fogbugz.com/f/cases/14133

14195 In the ChangeSorter: DNU when trying to get  a menu
	https://pharo.fogbugz.com/f/cases/14195

14199 RBFindBlockArgumentAssignment is sometimes wrong
	https://pharo.fogbugz.com/f/cases/14199'.
	self loadTogether: self script292 merge: false.
	self flushCaches.
