update40589
	"self new update40589"
	self withUpdateLog: '15268 Categorise some uncategorized methods in Slot examples
	https://pharo.fogbugz.com/f/cases/15268

15261 Generator: Move example from comment to method
	https://pharo.fogbugz.com/f/cases/15261

15266 browser version in nautilus without a method selected throws a DNU
	https://pharo.fogbugz.com/f/cases/15266'.
	self loadTogether: self script589 merge: false.
	self flushCaches.
