update40256
	"self new update40256"
	self withUpdateLog: '14069 Finish cleaning RGFactory
	https://pharo.fogbugz.com/f/cases/14069

14077 Move PseudoClassOrganization close to PseudoClass
	https://pharo.fogbugz.com/f/cases/14077

13738 MNU: CompiledMethod>>hasRun
	https://pharo.fogbugz.com/f/cases/13738

13705 Shared pool incorrectly defined as global
	https://pharo.fogbugz.com/f/cases/13705'.
	self loadTogether: self script256 merge: false.
	self flushCaches.
