update40541
	"self new update40541"
	self withUpdateLog: '15089 Replace senders of String>>#subStrings: in Tool-Base
	https://pharo.fogbugz.com/f/cases/15089

15092 Replace senders of String>>#subStrings: in Nautilus
	https://pharo.fogbugz.com/f/cases/15092

15088 Replace senders of String>>#subStrings: in ConfigurationCommandLineHandler-Core
	https://pharo.fogbugz.com/f/cases/15088

15087 Replace senders of String>>#subStrings: in Slot
	https://pharo.fogbugz.com/f/cases/15087'.
	self loadTogether: self script541 merge: false.
	self flushCaches.
