update40538
	"self new update40538"
	self withUpdateLog: '15054 Move Finalization Classes in Collections Weak to System-Finalization
	https://pharo.fogbugz.com/f/cases/15054

15073 Merge ClassInstaller>>updateInstancesFrom:to: and TClassDescription>>updateInstances:from:  
	https://pharo.fogbugz.com/f/cases/15073

15056 Moving dependency Slot  -> Reflectivity
	https://pharo.fogbugz.com/f/cases/15056'.
	self loadTogether: self script538 merge: false.
	self flushCaches.
