update40562
	"self new update40562"
	self withUpdateLog: '15124 Move String>>#lastIndexOfPKSignature: to Compression
	https://pharo.fogbugz.com/f/cases/15124

15147 change class comment template
	https://pharo.fogbugz.com/f/cases/15147

14885 Cant change name of a Spec tab after it has been opened
	https://pharo.fogbugz.com/f/cases/14885'.
	self loadTogether: self script562 merge: false.
	self flushCaches.
