update40147
	"self new update40147"
	self withUpdateLog: '13747 EventHandlerPlus -> MouseOverEventHandler
	https://pharo.fogbugz.com/f/cases/13747

13749 SimpleBallonMorph has just one initialize and one user :)
	https://pharo.fogbugz.com/f/cases/13749

13744 Move to raises a DNU 
	https://pharo.fogbugz.com/f/cases/13744
	
13748 MoveFullScreenTo Morphi-Widgets-Windows since this is its only user
	https://pharo.fogbugz.com/f/cases/13748	

'.
	self loadTogether: self script147 merge: false.
	self flushCaches.
self cleanRepositories.
