update40357
	"self new update40357"
	self withUpdateLog: '14401 GTIRBrowser shows only decompiled source 
	https://pharo.fogbugz.com/f/cases/14401

14406 Replace Announcer>>#on:do:s senders in SUnit-Tests
	https://pharo.fogbugz.com/f/cases/14406

14408 Replace Announcer>>#on:do:s senders in Versionner-Tests-Core-Model
	https://pharo.fogbugz.com/f/cases/14408

14394 RBConfigurableFormatter>>newLinesBeforeStartingAt: fails if originalSource is nil
	https://pharo.fogbugz.com/f/cases/14394'.
	self loadTogether: self script357 merge: false.
	self flushCaches.
