update40275
	"self new update40275"
	self withUpdateLog: '14129 Use Announcer>>#when:send:to: in Spec-Debugger
	https://pharo.fogbugz.com/f/cases/14129

14124 Remove SystemAnnouncer subclass NautilusAnnouncer
	https://pharo.fogbugz.com/f/cases/14124

14126 Remove SystemAnnouncer subclass GroupAnnouncer
	https://pharo.fogbugz.com/f/cases/14126

10148 IRVisitor and IRInterpreter
	https://pharo.fogbugz.com/f/cases/10148'.
	self loadTogether: self script275 merge: false.
	self flushCaches.
