update40323
	"self new update40323"
	self withUpdateLog: '14297 Kernel fixes for Spur
	https://pharo.fogbugz.com/f/cases/14297

14302 Replace Announcer>>#on:send:to:s senders in NewValueHolder
	https://pharo.fogbugz.com/f/cases/14302

14291 browse open a class side browser
	https://pharo.fogbugz.com/f/cases/14291

14289 MNU in Finder>>computeWithMethodFinder:
	https://pharo.fogbugz.com/f/cases/14289'.
	self loadTogether: self script323 merge: false.
	self flushCaches.
