update40347
	"self new update40347"
	self withUpdateLog: '14364 tiny code critique cleanup in Ring
	https://pharo.fogbugz.com/f/cases/14364

14358 PseudoClass DNU printHierarchy in FileContentsBrowser
	https://pharo.fogbugz.com/f/cases/14358

14254 AST method replaceWith: does not change source interval
	https://pharo.fogbugz.com/f/cases/14254'.
	self loadTogether: self script347 merge: false.
	self flushCaches.
