update40586
	"self new update40586"
	self withUpdateLog: '13201 Hard to start a tutorial in Pharo
	https://pharo.fogbugz.com/f/cases/13201

15240 Stuck SHTextStyler semaphores
	https://pharo.fogbugz.com/f/cases/15240

15238 Add an assertion to check if a collection has same elements as another collection
	https://pharo.fogbugz.com/f/cases/15238'.
	self loadTogether: self script586 merge: false.
	self flushCaches.
