update40454
	"self new update40454"
	self withUpdateLog: '14764 Review DisplayScreen>>release
	https://pharo.fogbugz.com/f/cases/14764

14763 RBRefactoryChangeManager>>#release method call order
	https://pharo.fogbugz.com/f/cases/14763

14714 StartupPreferencesLoader class comment references class StartupLoader
	https://pharo.fogbugz.com/f/cases/14714

14747 Beside <script> pragma also allow <script: someActionCode> pragma in a method
	https://pharo.fogbugz.com/f/cases/14747'.
	self loadTogether: self script454 merge: false.
	self flushCaches.
