update40281
	"self new update40281"
	self withUpdateLog: '14153 Replace Announcer>>#on:send:to:s senders in Morphic-Base
	https://pharo.fogbugz.com/f/cases/14153

14150 Replace Announcer>>#on:send:tos senders in Morphic-Core
	https://pharo.fogbugz.com/f/cases/14150

14149 IRDecompiler creates an extended method state object for all methods
	https://pharo.fogbugz.com/f/cases/14149

14147 add Symbolic tab to inspector for IRMethod
	https://pharo.fogbugz.com/f/cases/14147'.
	self loadTogether: self script281 merge: false.
	self flushCaches.
