update40257
	"self new update40257"
	self withUpdateLog: '14061 windows systemfonts : wrong path in guessWindowsFontFolderPath
	https://pharo.fogbugz.com/f/cases/14061

13131 Spec weirdness > MNU ToolDockingBarMorph>>popupEvent:in: on right click on button
	https://pharo.fogbugz.com/f/cases/13131

14072 Failing test: BlockClosureTest>>#testTallyInstructions
	https://pharo.fogbugz.com/f/cases/14072'.
	self loadTogether: self script257 merge: false.
	self flushCaches.
