update40300
	"self new update40300"
	self withUpdateLog: '13457 The Implementors of  browser adds all methods added to its list
	https://pharo.fogbugz.com/f/cases/13457

14204 OCStoreIntoReadOnlyVariableError: VersionnerProjectPanel>>#initializeGroupsWidget:
	https://pharo.fogbugz.com/f/cases/14204

14224 add #symbolicBytecodes to CompiledMethod and clean up InstructionPrinter a little
	https://pharo.fogbugz.com/f/cases/14224

'.
	self loadTogether: self script300 merge: false.
	self flushCaches.
self cleanRepositories.
