update40471
	"self new update40471"
	self withUpdateLog: '14667 PackageTreeNautilus openOnMethod: not refreshing correctly
	https://pharo.fogbugz.com/f/cases/14667

14848 "Add required package" in Monticello should use the SearchFacade
	https://pharo.fogbugz.com/f/cases/14848

14842 cleaning removeClass
	https://pharo.fogbugz.com/f/cases/14842

14837 Code pane context menu shows superfluous items when inside class NautilusRefactoring
	https://pharo.fogbugz.com/f/cases/14837'.
	self loadTogether: self script471 merge: false.
	self flushCaches.
