update40289
	"self new update40289"
	self withUpdateLog: '14191 Add #deselectAll to TreeModel
	https://pharo.fogbugz.com/f/cases/14191

14188 DNU when moving a method to a package
	https://pharo.fogbugz.com/f/cases/14188

14187 Replace Announcer>>#on:send:to:s senders in Keymapping-Pragmas
	https://pharo.fogbugz.com/f/cases/14187

14184 Replace Announcer>>#on:send:to:s senders in GroupManager
	https://pharo.fogbugz.com/f/cases/14184

14185 Replace Announcer>>#on:send:to:s senders in Kernel
	https://pharo.fogbugz.com/f/cases/14185

14186 remove AllowBlockArgumentAssignment from CCompilerContext
	https://pharo.fogbugz.com/f/cases/14186'.
	self loadTogether: self script289 merge: false.
	self flushCaches.
