update40165
	"self new update40165"
	self withUpdateLog: '13773 implement drawOnAthensCanvas on MenuItemMorph and MenuLineMorph
	https://pharo.fogbugz.com/f/cases/13773

13754 cleaning strings API
	https://pharo.fogbugz.com/f/cases/13754

13815 Finder: remove non-needed preference
	https://pharo.fogbugz.com/f/cases/13815

13826 Extended search... fooled by block arguments
	https://pharo.fogbugz.com/f/cases/13826

13789 AthensWrapMorph can not paint gradient fill
	https://pharo.fogbugz.com/f/cases/13789

13806 Remove ThreadSafeTranscriptPluggableTextMorph
	https://pharo.fogbugz.com/f/cases/13806

'.
	self loadTogether: self script165 merge: false.
	self flushCaches.
self cleanRepositories.
