update40568
	"self new update40568"
	self withUpdateLog: '15167 Fix: Class level should know about visible slots, layout knows all
	https://pharo.fogbugz.com/f/cases/15167

15166 More tests for Slots
	https://pharo.fogbugz.com/f/cases/15166

15172 Add String>>#allRangesOfSubstring:
	https://pharo.fogbugz.com/f/cases/15172

15175 Add FindReplaceService>>#findNextSubstring:inTextMorph:
	https://pharo.fogbugz.com/f/cases/15175

15165 Number>>#percent shouldnt force to Float
	https://pharo.fogbugz.com/f/cases/15165

15169 add some GT views to ReflectiveMethod
	https://pharo.fogbugz.com/f/cases/15169'.
	self loadTogether: self script568 merge: false.
	self flushCaches.
