update40303
	"self new update40303"
	self withUpdateLog: '14232 remove ByteCodeMethodConverter
	https://pharo.fogbugz.com/f/cases/14232

14225 implement #symbolic by printing the SymbolicBytecode....
	https://pharo.fogbugz.com/f/cases/14225

13318 no (strong) visual feedback for bytecode view while looking at a class definition
	https://pharo.fogbugz.com/f/cases/13318'.
	self loadTogether: self script303 merge: false.
	self flushCaches.
