update40563
	"self new update40563"
	self withUpdateLog: '13333 MCWorkingCopyBrowser>>addSlice references ScriptLoader
	https://pharo.fogbugz.com/f/cases/13333

15158 Move deprecated Methods to Deprecated40 package
	https://pharo.fogbugz.com/f/cases/15158

15083 We should have senders/implementors in the code menu
	https://pharo.fogbugz.com/f/cases/15083'.
	self loadTogether: self script563 merge: false.
	self flushCaches.
