update40485
	"self new update40485"
	self withUpdateLog: '14892 Slots: when  class is created, #installingIn: is not called
	https://pharo.fogbugz.com/f/cases/14892

14893 Slots: allSlots should filter hidden slots
	https://pharo.fogbugz.com/f/cases/14893

14888 Matrix>>rows:columns arguments are unclear
	https://pharo.fogbugz.com/f/cases/14888'.
	self loadTogether: self script485 merge: false.
	self flushCaches.
