update40326
	"self new update40326"
	self withUpdateLog: '14313 Replace Announcer>>#on:send:to:s senders in RPackage-SystemIntegration
	https://pharo.fogbugz.com/f/cases/14313

14303 RemotesManager: Make more generally useful
	https://pharo.fogbugz.com/f/cases/14303

11065 Blocks should have some suggestions (at least the same as expressions so far)
	https://pharo.fogbugz.com/f/cases/11065'.
	self loadTogether: self script326 merge: false.
	self flushCaches.
