update40486
	"self new update40486"
	self withUpdateLog: '14904 Slot: hand the correct class to slot in #buildNewClass
	https://pharo.fogbugz.com/f/cases/14904

14899 add addSlot in testClassRespectsPolymorphismWithTrait
	https://pharo.fogbugz.com/f/cases/14899

14874 WorldState>>#interCyclePause: failed
	https://pharo.fogbugz.com/f/cases/14874

14895 Class Variable Refactoring -> Add produce error when pressing escape on dialog
	https://pharo.fogbugz.com/f/cases/14895'.
	self loadTogether: self script486 merge: false.
	self flushCaches.
