update40024
	"self new update40024"
	self withUpdateLog: '13308 MNU in EyeMorphViewer
	https://pharo.fogbugz.com/f/cases/13308

13242 SUnit shows wrong test result when Warning subclass signals on a test case method
	https://pharo.fogbugz.com/f/cases/13242

13340 tiny recategorization of uncategorised methods
	https://pharo.fogbugz.com/f/cases/13340

'.
	self loadTogether: self script24 merge: false.
	self flushCaches.
