update40353
	"self new update40353"
	self withUpdateLog: '14254 AST method replaceWith: does not change source interval
	https://pharo.fogbugz.com/f/cases/14254

14380 Replace Announcer>>#on:send:to:s senders in Tests
	https://pharo.fogbugz.com/f/cases/14380

14371 Traits should not be allowed to have nil as their category
	https://pharo.fogbugz.com/f/cases/14371'.
	self loadTogether: self script353 merge: false.
	self flushCaches.
