update40164
	"self new update40164"
	self withUpdateLog: '13787 Implement SequenceableCollection >> reverseWithIndexDo:
	https://pharo.fogbugz.com/f/cases/13787

13526 System Browser Add Class menu item doesn t offer current class as a superclass
	https://pharo.fogbugz.com/f/cases/13526

13814 DiffMethodReferenceConverter not needed
	https://pharo.fogbugz.com/f/cases/13814

13816 Unify default method templates + Shout critique clean
	https://pharo.fogbugz.com/f/cases/13816

13813 Nautilus Refactoring 7: rename methods 
	https://pharo.fogbugz.com/f/cases/13813

'.
	self loadTogether: self script164 merge: false.
	self flushCaches.
self cleanRepositories.
