update40053
	"self new update40053"
	self withUpdateLog: '13275 RBSmalllintChecker checks classes not defined in environment
	https://pharo.fogbugz.com/f/cases/13275

12551 Unused class CurveMorph
	https://pharo.fogbugz.com/f/cases/12551

13432 Small tool cleanup: VersionBrowser api, Implementors of
	https://pharo.fogbugz.com/f/cases/13432'.
	self loadTogether: self script53 merge: false.
	self flushCaches.
