update40028
	"self new update40028"
	self withUpdateLog: '13323 Cleaning PasteUpMorph mouseDown:
	https://pharo.fogbugz.com/f/cases/13323

13226 Inst Var Pull Up refactoring also shows superclass inst vars
	https://pharo.fogbugz.com/f/cases/13226

10935 AthensDemoMorph failing at figure9
	https://pharo.fogbugz.com/f/cases/10935

'.
	self loadTogether: self script28 merge: false.
	self flushCaches.
