update40504
	"self new update40504"
	self withUpdateLog: '14964 deprecated #anonymousSubclassOf:
	https://pharo.fogbugz.com/f/cases/14964

14975 Generate initialize methods should be in initialization protocol
	https://pharo.fogbugz.com/f/cases/14975

14967 MCFileTreeRepository does not implement #versionInfoFromVersionNamed: correctly
	https://pharo.fogbugz.com/f/cases/14967'.
	self loadTogether: self script504 merge: false.
	self flushCaches.
