update40516
	"self new update40516"
	self withUpdateLog: '14990 MonitorDelay>>#signalLock:afterMSecs:inMonitor:queue: should return MonitorDelay object
	https://pharo.fogbugz.com/f/cases/14990
	
15003 Bytecode Gen for Property Slot + small fixes reflectivity
	https://pharo.fogbugz.com/f/cases/15003
	
15004 Add ProcessLocalSlot
	https://pharo.fogbugz.com/f/cases/15004'.
	self loadTogether: self script516 merge: false.
	self flushCaches.
self cleanRepositories.
