update40348
	"self new update40348"
	self withUpdateLog: '13113 remove generateSpecFormat
	https://pharo.fogbugz.com/f/cases/13113

14366 HDTestReport>>#initializeOn: bad initialisation of suiteTime
	https://pharo.fogbugz.com/f/cases/14366

14365 missing #callPrimitive: method in OCDecompiler
	https://pharo.fogbugz.com/f/cases/14365'.
	self loadTogether: self script348 merge: false.
	self flushCaches.
