update40271
	"self new update40271"
	self withUpdateLog: '14100 use Announcer>>#when:do: and Announcer>>#when:send:to in Spec-Core
	https://pharo.fogbugz.com/f/cases/14100

14116 RGDefinition is mispelled and its comment doesnt make sense
	https://pharo.fogbugz.com/f/cases/14116

14101 Use Announcer>>#when:send:to: in Spec-MorphicAdapters
	https://pharo.fogbugz.com/f/cases/14101

14102 Use Announcer>>#when:send:to: in Spec-Tools
	https://pharo.fogbugz.com/f/cases/14102

12841 #testDebuggerTempAccess failures
	https://pharo.fogbugz.com/f/cases/12841'.
	self loadTogether: self script271 merge: false.
	self flushCaches.
