update40472
	"self new update40472"
	self withUpdateLog: '14843 Refactoring "Deprecate" should use the SearchFacade
	https://pharo.fogbugz.com/f/cases/14843

14820 Add flag RBRenameInstanceVariableRefactoring
	https://pharo.fogbugz.com/f/cases/14820

14849 The printing of a file reference of the working directory under windows throws an error
	https://pharo.fogbugz.com/f/cases/14849

14831 Improve file system to know which kind of fileStore is it (in memory or on disk)
	https://pharo.fogbugz.com/f/cases/14831

14846 MakeRelative: method applied on two relative paths is not working
	https://pharo.fogbugz.com/f/cases/14846'.
	self loadTogether: self script472 merge: false.
	self flushCaches.
