update40546
	"self new update40546"
	self withUpdateLog: '15014 Kommitter default size and layout not appropriate
	https://pharo.fogbugz.com/f/cases/15014

12330 Rendering artifacts with scaled ImageMorph
	https://pharo.fogbugz.com/f/cases/12330

15080 ProgressBar completion should resize when widget is resized
	https://pharo.fogbugz.com/f/cases/15080

15009 allow to set title in RemotesManager
	https://pharo.fogbugz.com/f/cases/15009'.
	self loadTogether: self script546 merge: false.
	self flushCaches.
