update40588
	"self new update40588"
	self withUpdateLog: '15253 URL to book in Tutorial is wrong
	https://pharo.fogbugz.com/f/cases/15253

14974 failing test testScrollToLargeX
	https://pharo.fogbugz.com/f/cases/14974

15241 Nautilus does not display catalogDescrption help text for many packages when moused over/clicked
	https://pharo.fogbugz.com/f/cases/15241'.
	self loadTogether: self script588 merge: false.
	self flushCaches.
