update40260
	"self new update40260"
	self withUpdateLog: '14028 PluggableThreePhaseButtonMorph should be packaged with Morphic-Widgets-Basic
	https://pharo.fogbugz.com/f/cases/14028

13668 remove the last StringHolder references
	https://pharo.fogbugz.com/f/cases/13668

13635 Package Spec-Extensions just contains one accessor --> can be moved to the class
	https://pharo.fogbugz.com/f/cases/13635

5625 TextDiffBuilder in System-FilePackage ?
	https://pharo.fogbugz.com/f/cases/5625'.
	self loadTogether: self script260 merge: false.
	self flushCaches.
