update40512
	"self new update40512"
	self withUpdateLog: '14990 MonitorDelay>>#signalLock:afterMSecs:inMonitor:queue: should return MonitorDelay object
	https://pharo.fogbugz.com/f/cases/14990

14984 Improve protocol names in ComposableModel and subclasses
	https://pharo.fogbugz.com/f/cases/14984

14996 LinkedList>>#select:thenCollect: is slow
	https://pharo.fogbugz.com/f/cases/14996

14995 script: Pragma is also acceptable for non-unary methods
	https://pharo.fogbugz.com/f/cases/14995'.
	self loadTogether: self script512 merge: false.
	self flushCaches.
