update40274
	"self new update40274"
	self withUpdateLog: '14125 Remove SystemAnnouncer subclass TestAnnouncer
	https://pharo.fogbugz.com/f/cases/14125

14122 Classes in Morphic-Examples should include real #example methods
	https://pharo.fogbugz.com/f/cases/14122

12973 ChangeSorter CMD-W with menu open causes error
	https://pharo.fogbugz.com/f/cases/12973

14120 decompiler view for GTInspector
	https://pharo.fogbugz.com/f/cases/14120'.
	self loadTogether: self script274 merge: false.
	self flushCaches.
