update40270
	"self new update40270"
	self withUpdateLog: '14115 Merge RGDefinition and RGNamedDefinition
	https://pharo.fogbugz.com/f/cases/14115

14114 use SizeMismatch, not just #error
	https://pharo.fogbugz.com/f/cases/14114

13518 Strange color and wrong positions in the Find & Replace dialog 
	https://pharo.fogbugz.com/f/cases/13518'.
	self loadTogether: self script270 merge: false.
	self flushCaches.
