update40420
	"self new update40420"
	self withUpdateLog: '14634 Package Filter in Nautilus should use the last used filter when a new window is opened
	https://pharo.fogbugz.com/f/cases/14634

14620 Jump from history entry does not work
	https://pharo.fogbugz.com/f/cases/14620

14630 Pipes method highlighting 
	https://pharo.fogbugz.com/f/cases/14630'.
	self loadTogether: self script420 merge: false.
	self flushCaches.
