update40423
	"self new update40423"
	self withUpdateLog: '14644 Make NewVersionBrowser using a RingDefinition instead of class/selector
	https://pharo.fogbugz.com/f/cases/14644

14648 Include CubeHelix gradient definition
	https://pharo.fogbugz.com/f/cases/14648

14653 removeing or renaming raises an exception
	https://pharo.fogbugz.com/f/cases/14653'.
	self loadTogether: self script423 merge: false.
	self flushCaches.
