update40278
	"self new update40278"
	self withUpdateLog: '13718 Failing test: RBExtractMethodTest>>#testExtractMethodThatMovesTemporaryVariable 
	https://pharo.fogbugz.com/f/cases/13718

13222 HDLintReport generates invalid output
	https://pharo.fogbugz.com/f/cases/13222

12774 DialogGroupAdderUI "item to add" list should be sorted, has superfluous periods after class names
	https://pharo.fogbugz.com/f/cases/12774

14134 ecompletion raises DNU for some input
	https://pharo.fogbugz.com/f/cases/14134'.
	self loadTogether: self script278 merge: false.
	self flushCaches.
