update40287
	"self new update40287"
	self withUpdateLog: '14179 deprecate the method in UIManager "deprecated" category
	https://pharo.fogbugz.com/f/cases/14179

14162 Replace Announcer>>#on:send:to:s senders in Morphic-Widgets-Tree
	https://pharo.fogbugz.com/f/cases/14162

14173 remove #allowBlockArgumentAssignment preference
	https://pharo.fogbugz.com/f/cases/14173'.
	self loadTogether: self script287 merge: false.
	self flushCaches.
