update40453
	"self new update40453"
	self withUpdateLog: '14762 Deprecate Stream>>isMessageStream
	https://pharo.fogbugz.com/f/cases/14762

14761 Move Collections-Strings deprecated methods to Deprecated40 package
	https://pharo.fogbugz.com/f/cases/14761

14758 Simplify MCClassDefinition>>#createClass
	https://pharo.fogbugz.com/f/cases/14758'.
	self loadTogether: self script453 merge: false.
	self flushCaches.
