update40537
	"self new update40537"
	self withUpdateLog: '15050 Move Text conversion methods to Text Converter package
	https://pharo.fogbugz.com/f/cases/15050

15069 endless recursion in DockingBarMorph add:icon:subMenu:
	https://pharo.fogbugz.com/f/cases/15069

15053 Moved dependency Dictionary -> Slot to slot package
	https://pharo.fogbugz.com/f/cases/15053'.
	self loadTogether: self script537 merge: false.
	self flushCaches.
