update40153
	"self new update40153"
	self withUpdateLog: '13763 SyntaxErrorNotification: errorMessage ivar not needed 
	https://pharo.fogbugz.com/f/cases/13763

13782 add preference the DEBUG menu entires of Nautilus 
	https://pharo.fogbugz.com/f/cases/13782

13767 packagetree changes visible selection even if okToChange is false
	https://pharo.fogbugz.com/f/cases/13767

13778 Workspace: fix non-declared temp vars
	https://pharo.fogbugz.com/f/cases/13778

13781 class Refactor not needed
	https://pharo.fogbugz.com/f/cases/13781

'.
	self loadTogether: self script153 merge: false.
	self flushCaches.
self cleanRepositories.
