update40251
	"self new update40251"
	self withUpdateLog: '3841 FinderUI gets out of sync when more than one Finder open
	https://pharo.fogbugz.com/f/cases/3841

10307 Monticello FTP repo should not keep username and should behave like MC HTTP
	https://pharo.fogbugz.com/f/cases/10307

14067 More cleaning of Ring Factory
	https://pharo.fogbugz.com/f/cases/14067'.
	self loadTogether: self script251 merge: false.
	self flushCaches.
