update40264
	"self new update40264"
	self withUpdateLog: '13867 MessageBrowser does not inform about certain syntax error
	https://pharo.fogbugz.com/f/cases/13867

13293 We should add definedSelectors and extensionSelectors to ClassDescription
	https://pharo.fogbugz.com/f/cases/13293

13934 Extra characters in string returned by String class>>new:streamContents:
	https://pharo.fogbugz.com/f/cases/13934'.
	self loadTogether: self script264 merge: false.
	self flushCaches.
