update40494
	"self new update40494"
	self withUpdateLog: '14940 timeToRunWithoutGC broken
	https://pharo.fogbugz.com/f/cases/14940

14946 Replace senders of String>>#subStrings: in Tool-Finder
	https://pharo.fogbugz.com/f/cases/14946

14937 better comments and test for Matrix
	https://pharo.fogbugz.com/f/cases/14937

14060 MNU: receiver of "stepToCallee" is nil
	https://pharo.fogbugz.com/f/cases/14060'.
	self loadTogether: self script494 merge: false.
	self flushCaches.
