update40518
	"self new update40518"
	self withUpdateLog: '15006 RBPatternVariableNode>>initializePatternVariables(name is shadowed)
	https://pharo.fogbugz.com/f/cases/15006
	
15001 Update Zinc-Resource-Meta-FileSystem
	https://pharo.fogbugz.com/f/cases/15001
	
10741 Can not upload slice dependency already in repo
	https://pharo.fogbugz.com/f/cases/10741
	'.
	self loadTogether: self script518 merge: false.
	self flushCaches.
self cleanRepositories.
