update40315
	"self new update40315"
	self withUpdateLog: '14272 #_foo: isBinary ---> true
	https://pharo.fogbugz.com/f/cases/14272

14221 Tests around Graphics
	https://pharo.fogbugz.com/f/cases/14221

14271 RBCodeCruftLeftInMethodsRule>>initialize and RBAllAnyNoneSatisfyRule>>name have spelling errors
	https://pharo.fogbugz.com/f/cases/14271'.
	self loadTogether: self script315 merge: false.
	self flushCaches.
