update40554
	"self new update40554"
	self withUpdateLog: '14829 Spec MenuModel submenu not working
	https://pharo.fogbugz.com/f/cases/14829

14972 SpecWindow: AboutText  always shows WindowModels class comment
	https://pharo.fogbugz.com/f/cases/14972

6488 DropListModel>>whenSelectionChanged:
	https://pharo.fogbugz.com/f/cases/6488

15067 TestReviver open does not work in Pharo4.0 Latest update: #40535
	https://pharo.fogbugz.com/f/cases/15067'.
	self loadTogether: self script554 merge: false.
	self flushCaches.
