update40240
	"self new update40240"
	self withUpdateLog: '14019 add critics rule for #withFirstCharacterDownshifted-> #uncapitalized
	https://pharo.fogbugz.com/f/cases/14019

14049 add String>>substrings: and lint rule for #subStrings:
	https://pharo.fogbugz.com/f/cases/14049

14035 openWorldWithSpec not taking over the world
	https://pharo.fogbugz.com/f/cases/14035

14045 Categorize classes in System-Announcements
	https://pharo.fogbugz.com/f/cases/14045'.
	self loadTogether: self script240 merge: false.
	self flushCaches.
