Morph subclass: #FTTableMorph
	instanceVariableNames: 'container verticalScrollBar backgroundColor selectionColor showIndex dataSource intercellSpacing rowHeight selectedRowIndexes highlightedRowIndexes selectionStrategy columns secondarySelectionColor headerColor showColumnHeaders search allowsDeselection needToggleAtMooseUp'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Morphic-Widgets-FastTable'