Morph subclass: #FTTableMorph
	instanceVariableNames: 'container verticalScrollBar selectionColor showIndex dataSource intercellSpacing rowHeight selectedRowIndexes highlightedRowIndexes selectionStrategy columns secondarySelectionColor headerColor showColumnHeaders allowsDeselection needToggleAtMouseUp function resizable'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Morphic-Widgets-FastTable'