Morph subclass: #FTTableMorph
	instanceVariableNames: 'container verticalScrollBar backgroundColor selectionColor showIndex dataSource intercellSpacing rowHeight selectedRowIndexes highlightedRowIndexes selectionStrategy columns secondarySelectionColor headerColor showColumnHeaders allowsDeselection needToggleAtMooseUp function'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Morphic-Widgets-FastTable'