public
commentForCurrentUpdate
 ^ 'Issue 6942:	Integer >> asArray, asByteArray, asByteArrayOfSize in usuitable package
	http://code.google.com/p/pharo/issues/detail?id=6942
	
Issue 6937:	RGMonticelloTest in unsuitable package
	http://code.google.com/p/pharo/issues/detail?id=6937
	
Issue 6940:	BehaviorTest >> testComposedBy dependent on Morphic
	http://code.google.com/p/pharo/issues/detail?id=6940'