pharo - updates
update20306
	"self new update20306"
	self withUpdateLog: 'Issue 6731:	FileDialogWindow DNU - FS related
	http://code.google.com/p/pharo/issues/detail?id=6731
	
Issue 6730:	Better way to define platform specific shortcuts
	http://code.google.com/p/pharo/issues/detail?id=6730
	
Issue 6632:	assert:equals: reverse the order of the printed arguments
	http://code.google.com/p/pharo/issues/detail?id=6632'.
	self loadTogether: self script293 merge: false.
	self flushCaches.
