pharo - updates
update20517
	"self new update20517"
	self withUpdateLog: 'Issue 7426:	Failing tests in ZnFileUrlTest on Windows
	http://code.google.com/p/pharo/issues/detail?id=7426
	
Issue 7371:	Archive>>addTree: removingFirstCharacters: match: do not work
	http://code.google.com/p/pharo/issues/detail?id=7371
	
Issue 7338:	Failing test: RPackageReleaseTest>>#testRPackageOrganizer
	http://code.google.com/p/pharo/issues/detail?id=7338
	
Issue 7292:	Autocomplete partial matches
	http://code.google.com/p/pharo/issues/detail?id=7292
	
Issue 6885:	Image cant starts and hangs when cant find required free type font files
	http://code.google.com/p/pharo/issues/detail?id=6885'.
	self loadTogether: self script494 merge: false.
	self flushCaches.
