pharo - updates
update20489
	"self new update20489"
	self withUpdateLog: 'Issue 7296:	visual feedback from class side when a class has class side methods
	http://code.google.com/p/pharo/issues/detail?id=7296
	
Issue 6100:	Too many This group already exists
	http://code.google.com/p/pharo/issues/detail?id=6100
	
Issue 5896:	[ENH]: Nautilus icon for method breakpoints
	http://code.google.com/p/pharo/issues/detail?id=5896'.
	self loadTogether: self script467 merge: false.
	self flushCaches.
