pharo - updates
update20159
	"self new update20159"
	self withUpdateLog: 'Issue 5590:	Rounding a float: 10.123 round: 2 => 10.12
	http://code.google.com/p/pharo/issues/detail?id=5590
	
Issue 5956:	Let morphs announce when focus changes
	http://code.google.com/p/pharo/issues/detail?id=5956
	
Issue 6133:	Improvement in Finder
	http://code.google.com/p/pharo/issues/detail?id=6133
	
Issue 6128:	Spec: ClassMethodBrowser example gives a MNU due to missing setter
	http://code.google.com/p/pharo/issues/detail?id=6128'.
	self loadTogether: self script149 merge: false.
	self flushCaches.
