pharo - updates
update20399
	"self new update20399"
	self withUpdateLog: 'Issue 6929:	Undeclared ManifestManifestResourcesTests
	http://code.google.com/p/pharo/issues/detail?id=6929
	
Issue 6982:	debugging an empty method raises an error
	http://code.google.com/p/pharo/issues/detail?id=6982
	
Issue 6979:	LoggingSystemProgressItemMorph and Job>>#loggingProgress shuld be deprecate
	http://code.google.com/p/pharo/issues/detail?id=6979
	
Issue 6980:	direct use of RecentMessageList
	http://code.google.com/p/pharo/issues/detail?id=6980
	
Issue 6976:	move asUrl to Network-Url package
	http://code.google.com/p/pharo/issues/detail?id=6976'.
	self loadTogether: self script378 merge: false.
	self flushCaches.
