pharo - updates
update20377
	"self new update20377"
	self withUpdateLog: 'Issue 6839:	ReleaseTest>> testObsoleteClasses
	http://code.google.com/p/pharo/issues/detail?id=6839
	
Issue 4038:	MorphicUIManager contains widget definitions
	http://code.google.com/p/pharo/issues/detail?id=4038
	
Issue 6905:	SUnit-UITesting
	http://code.google.com/p/pharo/issues/detail?id=6905'.
	self loadTogether: self script357 merge: false.
	self flushCaches.
