pharo - updates
update20496
	"self new update20496"
	self withUpdateLog: 'Issue 7349:	rootApplication does not exist in Pharo. Thanks Vanessa Pena and Pablo Estefo. 
	http://code.google.com/p/pharo/issues/detail?id=7349
	
Issue 7349:	rootApplication does not exist in Pharo. Thanks Vanessa Pena and Pablo Estefo. 
	http://code.google.com/p/pharo/issues/detail?id=7349
	
Issue 7356:	New comment in MessageTally> Thanks Alexandre and Milton. 
	http://code.google.com/p/pharo/issues/detail?id=7356.

Issue 7328:	diffmorph does not shows the middle separator. Thanks Sean De Nigris.
	http://code.google.com/p/pharo/issues/detail?id=7328'.
	self loadTogether: self script474 merge: false.
	self flushCaches.
