pharo - updates
update20357
	"self new update20357"
	self withUpdateLog: 'Issue 6822:	Code Completion fails on Traits
	http://code.google.com/p/pharo/issues/detail?id=6822
	
Issue 6854:	Improve Gofer Tests: add smalltalkhub repository test
	http://code.google.com/p/pharo/issues/detail?id=6854
	
Issue 4690:	progress bar position should be configurable
	http://code.google.com/p/pharo/issues/detail?id=4690'.
	self loadTogether: self script339 merge: false.
	self flushCaches.
