pharo - updates
update20516
	"self new update20516"
	self withUpdateLog: 'Issue 7408:	Nautilus create Package Dialog allows Extension names
	http://code.google.com/p/pharo/issues/detail?id=7408
	
Issue 7368:	MCSubDirectoryRepository>>findFullNameForWriting:
	http://code.google.com/p/pharo/issues/detail?id=7368
	
Issue 7367:	Add support for Phexample to Nautilus and cleanup testing for test methods a bit
	http://code.google.com/p/pharo/issues/detail?id=7367
	
Issue 7208:	Opening Critics Browser from the Package context menu results in an error
	http://code.google.com/p/pharo/issues/detail?id=7208'.
	self loadTogether: self script493 merge: false.
	self flushCaches.
