pharo - updates
update20256
	"self new update20256"
	self withUpdateLog: 'Issue 6573:	[ENH]: Port Fix 6562 to Pharo 2.0
	http://code.google.com/p/pharo/issues/detail?id=6573

Issue 6572:	more selection out of bounds fixes for List morphs
	http://code.google.com/p/pharo/issues/detail?id=6572
		
Issue 6533:	Spec fixed in KMDescription
	http://code.google.com/p/pharo/issues/detail?id=6533
	
Issue 6399:	Small Keymapping Improvement
	http://code.google.com/p/pharo/issues/detail?id=6399'.
	self loadTogether: self script243 merge: false.
	self flushCaches.
