pharo - updates
update20539
	"self new update20539"
	self withUpdateLog: 'Issue 7488:	Failing test: #testMethodsWithUnboundGlobals
	http://code.google.com/p/pharo/issues/detail?id=7488
	
Issue 7486:	Autocompletion fails when superclass is nil. (Generally Traits)
	http://code.google.com/p/pharo/issues/detail?id=7486

Issue 7482:	Starting from #20526, cannot remove non-empty category
	http://code.google.com/p/pharo/issues/detail?id=7482
	
Issue 7446:	ClassDescription >> correspondingForTest is local
	http://code.google.com/p/pharo/issues/detail?id=7446'.
	self loadTogether: self script514 merge: false.
	self flushCaches.
