pharo - updates
update20484
	"self new update20484"
	self withUpdateLog: 'Issue 7307:	RGMethodDefinition string representation different from CompiledMethod
	http://code.google.com/p/pharo/issues/detail?id=7307
	
Issue 7306:	un-deprecate OSPlatform osVersion for compatibility
	http://code.google.com/p/pharo/issues/detail?id=7306
	
Issue 7303:	[ENH]: SystemWindow>>#openModal
	http://code.google.com/p/pharo/issues/detail?id=7303
	
Issue 7108:	Timing riddle
	http://code.google.com/p/pharo/issues/detail?id=7108
	
Issue 6608:	FileReference>>item
	http://code.google.com/p/pharo/issues/detail?id=6608'.
	self loadTogether: self script462 merge: false.
	self flushCaches.
