pharo - updates
update20224
	"self new update20224"
	self withUpdateLog: 'Issue 6398:	MCPackageManager class >> methodMoved: uses old SystemChangeNotifier
	http://code.google.com/p/pharo/issues/detail?id=6398&
	
Issue 6390:	Spotlight throws "TextMorphForFieldView DNU #lostFocusBlock:"
	http://code.google.com/p/pharo/issues/detail?id=6390
	
Issue 6362:	Failing test: KMDispatcherTestCase.testBuffering
	http://code.google.com/p/pharo/issues/detail?id=6362
	
Issue 5993:	Change in Scrollbar behavior
	http://code.google.com/p/pharo/issues/detail?id=5993'.
	self loadTogether: self script212 merge: false.
	self flushCaches.
