pharo - updates
update20209
	"self new update20209"
	self withUpdateLog: 'Issue 6356:	some cleanups related to methods moved away from SmalltalkImage (vm and os related)
	http://code.google.com/p/pharo/issues/detail?id=6356
	
Issue 6355:	ClassCommentVersionBrowser should not shout the text
	http://code.google.com/p/pharo/issues/detail?id=6355
		
Issue 6289:	New KM version
	http://code.google.com/p/pharo/issues/detail?id=6289
	
Issue 5617:	Add a way to define in only one place menus and shortcuts
	http://code.google.com/p/pharo/issues/detail?id=5617
	
Issue 5356:	Make border of windows widther
	http://code.google.com/p/pharo/issues/detail?id=5356'.
	self loadTogether: self script199 merge: false.
	self flushCaches.
