pharo - updates
update20334
	"self new update20334"
	self withUpdateLog: 'Issue 6790:	MC SaveDialog fork fix
	http://code.google.com/p/pharo/issues/detail?id=6790
	
Issue 6788:	Improve Regex match/search/matchprefix methods comments
	http://code.google.com/p/pharo/issues/detail?id=6788
	
Issue 6787:	Finder Cleanup 2
	http://code.google.com/p/pharo/issues/detail?id=6787
	
Issue 6756:	Type code in editor go crash and show red panel
	http://code.google.com/p/pharo/issues/detail?id=6756'.
	self loadTogether: self script316 merge: false.
	self flushCaches.
