pharo - updates
update20487
	"self new update20487"
	self withUpdateLog: 'Issue 7323:	Add commandName to DefaultCommandLineHandler
	http://code.google.com/p/pharo/issues/detail?id=7323
	
Issue 7309:	unused and unnecessary instance side instance variable in ASTCache.
	http://code.google.com/p/pharo/issues/detail?id=7309
	
Issue 7206:	Error when Extracting a ZipArchive in 2.0
	http://code.google.com/p/pharo/issues/detail?id=7206
	
Issue 7277:	inspectOnce is not working anymore
	http://code.google.com/p/pharo/issues/detail?id=7277'.
	self loadTogether: self script465 merge: false.
	self flushCaches.
