pharo - updates
update20483
	"self new update20483"
	self withUpdateLog: 'Issue 7305:	Adding username/password support to ConfigurationCommandLineHandler>>gofer	
	http://code.google.com/p/pharo/issues/detail?id=7305

Issue 7302:	the emergency evaluator revert functionality does not work
	http://code.google.com/p/pharo/issues/detail?id=7302
	
Issue 7300:	PreDebugWindow has two unused instance variables	
	http://code.google.com/p/pharo/issues/detail?id=7300'.
	self loadTogether: self script461 merge: false.
	RecentMessageList uniqueInstance registerToAnnouncements.
	self flushCaches.
