pharo - updates
update20444
	"self new update20444"
	self withUpdateLog: 'Issue 7154:	Better tab naming in config browser
	http://code.google.com/p/pharo/issues/detail?id=7154
	
Issue 7153:	DNU on a deprecated String progress display method
	http://code.google.com/p/pharo/issues/detail?id=7153
	
Issue 7152:	DNU when searching a Change Set in Change Sorter
	http://code.google.com/p/pharo/issues/detail?id=7152
	
Issue 7145:	simplify MethodContext>>#tempNamed:
	http://code.google.com/p/pharo/issues/detail?id=7145'.
	self loadTogether: self script423 merge: false.
	self flushCaches.
