shortcuts
buildExtraShortcutsOn: aBuilder
<keymap>

	(aBuilder shortcut: #openBrowser)
		category: #NautilusGlobalShortcuts
		default: $o command 
		do: [ Smalltalk tools browser open ]
		description: 'Open a new browser'.
		
	(aBuilder shortcut: #openBrowser)
		category: #NautilusGlobalShortcuts
		default: $o command 
		do: [ Smalltalk tools browser open ]
		description: 'Open a new browser'.
		
	