FT2Handle subclass: #FT2Face
	instanceVariableNames: 'numFaces faceIndex faceFlags styleFlags numGlyphs familyName styleName numFixedSizes availableSizes numCharmaps charmaps bbox unitsPerEm ascender descender height maxAdvanceWidth maxAdvanceHeight underlinePosition underlineThickness glyph encoding platformId encodingId size'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'FreeType-Base'