commentForCurrentUpdate
 ^ '15764 Clean up discouraged uses of SourceFiles and friends (1)
	https://pharo.fogbugz.com/f/cases/15764

12986 Increase speed of accessing sourceCode
	https://pharo.fogbugz.com/f/cases/12986

15589 Mouse selection issue in Rubric text editor
	https://pharo.fogbugz.com/f/cases/15589

15577 localHostName implementation does not use dedicated primitives
	https://pharo.fogbugz.com/f/cases/15577

15762 Cleaning nextChunk
	https://pharo.fogbugz.com/f/cases/15762

15758 Move users of gather: to flatCollect:
	https://pharo.fogbugz.com/f/cases/15758

15711 The File Browser has a Context Menu "Workspace with Contents". It opens an Edit Window (String Morph), but not a Workspace ... 
	https://pharo.fogbugz.com/f/cases/15711'