commentForCurrentUpdate
 ^ '17801 EditingState/RubEditingState >>#addUndoRecord:  sends a unimplemented message
	https://pharo.fogbugz.com/f/cases/17801

17534 Transcript does not work after image save and restart
	https://pharo.fogbugz.com/f/cases/17534

16274 Text-Core should not depend on Tool-Base
	https://pharo.fogbugz.com/f/cases/16274

17820 QualityAssistant v2.5.1
	https://pharo.fogbugz.com/f/cases/17820'