AbstractBasicWidget subclass: #TreeModel
	instanceVariableNames: 'treeModel childrenBlockHolder menuBlockHolder rootsHolder selectionHolder autoMultiSelection columnInset doubleClick evenRowColor isCheckList keyStroke multiSelection oddRowColor preferedPaneColor resizerWidth rowInset displayBlock rootNodeHolder columns treeUpdated iconBlock autoDeselection allowMenuOnNoItem'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Spec-Widgets'