public
commentForCurrentUpdate
 ^ 'Issue 6197:	Nautilus global shortcuts
	http://code.google.com/p/pharo/issues/detail?id=6197
	
Issue 6196:	KMDescription fixed
	http://code.google.com/p/pharo/issues/detail?id=6196
	
Issue 6195:	Change in AbstractTool
	http://code.google.com/p/pharo/issues/detail?id=6195
	
Issue 6194:	Failing test: #testDialectLocalizedException
	http://code.google.com/p/pharo/issues/detail?id=6194
	
Issue 6151:	Get rid of "Objects pointing to this value"
	http://code.google.com/p/pharo/issues/detail?id=6151'