pharo - updates
update20025
	"self new update20025"
	self withUpdateLog: 'Issue 5728:	Add voidCogVMState primitives
	http://code.google.com/p/pharo/issues/detail?id=5728
	
Issue 5727:	add how to use comment to SystemProgressBarMorph
	http://code.google.com/p/pharo/issues/detail?id=5727
	
Issue 5704:	 speed-up unwind-protects a little.
	http://code.google.com/p/pharo/issues/detail?id=5704
	
Issue 5605:	DateAndTimeTest>>testPrintStringNoOffset fails on pharo-one-click
	http://code.google.com/p/pharo/issues/detail?id=5605
	
Issue 5653:	SystemNavigation has unused class variable Default
	http://code.google.com/p/pharo/issues/detail?id=5653'.
	self loadTogether: self script19 merge: false.
	self flushCaches.
