pharo - updates
update20090
	"self new update20090"
	self withUpdateLog: 'Issue 5949:	ArrayedCollection >> bytesPerElement and bytesPerBasicElement cleaning
	http://code.google.com/p/pharo/issues/detail?id=5949
	
Issue 5946:	Failing test in SpecInterpreterTest
	http://code.google.com/p/pharo/issues/detail?id=5946
	
Issue 5484:	Unicode depending on zinc
	http://code.google.com/p/pharo/issues/detail?id=5484

Issue 5947:	PluggableTextMorphWithLimits should be moved close to PluggableTextMorph	
	http://code.google.com/p/pharo/issues/detail?id=5947'.
	self loadTogether: self script79 merge: false.
	self flushCaches.
