Object subclass: #MetacelloMCPartiallyLoadedStatus
	instanceVariableNames: 'hasNoPackage hasNoProject aProjectIsLoaded aPackageIsLoaded aLoadedProjectIsExact aLoadedPackageIsExact aLoadedProjectIsCurrent aLoadedPackageIsCurrent aLoadedProjectIsNotCurrent aLoadedPackageIsNotCurrent aProjectNotLoaded aPackageNotLoaded vrsnStatus abort'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Metacello-MC-Specs'