deprecated
getsIconContents
	"Private - Method generated with the content of the file /home/plantec/dvpt/Pharo/Sprint-10-09/Icons/gets.png"
	self deprecated: 'Do not use anymore' on: 'Pharo20' in: 'May 15, 2012'.
	^ 'iVBORw0KGgoAAAANSUhEUgAAABUAAAAUCAMAAABVlYYBAAADAFBMVEX///+XAJYymJiXlgAQ
EBAhISEAAFPK/8oAMZcAMmUAMssAMfwAMTFlMQBlZAAAZJcAl5cAy5gA/JcxlwBklwDLAJf8
AJdkl5eYmJjLmAD8lwCXADGXAGSXAMuXAPwxl8oymP+YlzKXl2SXMQCXZACYMpeXZJcxypcy
/5eYywCX/AAyZZhkZJfKl5f/mJgxMAAyZQAxADAxAGUxAJcyMphkAJdkMpgAZTEAlzEAZWUA
l2QAyzIA/DEAy2QA/GTKypfL/5j/ypj//ZgxAMsxAPxkAMtkAPzLADHLAGT8ADH8AGQymDIy
mGRlmDJkl2TLAMrKAPz8AMr8APxlmMtkl/+Xl8qYmP/KlzHLl2X/lzL/l2QyMjIxZDExMWQx
ZGRlADFkMTFlAGRkMWTLMQDLZAD8MQD8ZAAAZcsAmMsAZPwAl/wAy8sA/MoAyvwA/PwyywAx
/ABlywBk/ADKMZfLZZf/Mpf/ZJdly5dk/5eXypeY/5jLygDK/AD8ygD8/ACYMjKYZDKYMmSX
ZGSXMcqXZcuXMv+XZP8xysoy/8syy/8y//+XyjGY/zKYy2WX/2TKl8rLy8vKmP/Kyv//mMr/
ysr/mP3/yv0xMcoxZMoyMv8yZf9kMcplZctkMv9kZP/KMTHKZDHKMWTLZWX/MjL/ZDL/MmT/
ZGQxyjEy/zIxymQy/2VkyjFl/zJly2Vk/2TKMcrLZcrKMv/KZP//Msr/ZMr/Mv3/ZP1ly8tk
/8pkyv9k//+XysqY/8qYy/+Y///KyjHL/zLLymXK/2T/yzL//TL/ymT//WRDQ0NkZDHc3NzK
/////crt7e0PAACXAAAADwBlAAAAAJcAAGV2dnaHh4eqqqq6urpVVVVlZWUAAA8AACFDAABT
AAAAAMsAANsAAO0AAPwAADEAAEMAhwAAlwAAqgAAuQAAywAA2wAA7QAA/ADLAADbAADtAAD8
AAAAQwAAUwAAZQAAdQAhAAAxAACqAAC5AAAAIQAAMQB1AACHAAAAAKoAALkAAHUAAIcAAAA+
ZgN8AAABAHRSTlP/////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////fvXo
qAAAAEFJREFUeF6t0LsNADAIQ0HYf1GPkZ8UKeDXxRW6BnBkmsSdNNNUTuVUTgserbi14VL1
fFG/DS6DL+BjaAeahNafDE0vk9OGbfiMAAAAAElFTkSuQmCC'