update30586
	"self new update30586"
	self withUpdateLog: '12204 Pharo3Theme beCurrent
	https://pharo.fogbugz.com/f/cases/12204

12200 Rename RPackage does not rename class tags
	https://pharo.fogbugz.com/f/cases/12200

12182 Collection>>sumNumbers: should provide an alternative to failing sum:
	https://pharo.fogbugz.com/f/cases/12182'.
	self loadTogether: self script241 merge: false.
	Pharo3Theme beCurrent.
	self flushCaches.
