update30489
	"self new update30489"
	self withUpdateLog: '11893 move MCVersionLoader>>#versions
	https://pharo.fogbugz.com/f/cases/11893
	
11898 Move DialogWindowModel deprecated methods to Deprecated30 package	
	https://pharo.fogbugz.com/f/cases/11886
	
11810 undeclared MailSender
	https://pharo.fogbugz.com/f/cases/11810
	
11881 Metacello references non-existing classes FileDirectory SystemChangeNotifier and OSProcess
	https://pharo.fogbugz.com/f/cases/11881'.
	self loadTogether: self script144 merge: false.
	self flushCaches.
