update30532
	"self new update30532"
	self withUpdateLog: '12031 One should not ask for the glyphInfo of a fallbackFont
	https://pharo.fogbugz.com/f/cases/12031
	
12029 ScaledDecimal with unspecified scale should auto-adjust their scale
	https://pharo.fogbugz.com/f/cases/12029
	
12023 Remove duplicated code in 3 implementors of #getPreambleFrom:at:
	https://pharo.fogbugz.com/f/cases/12023
	'.
	self loadTogether: self script187 merge: false.
	self flushCaches.
