update30613
	"self new update30613"
	self withUpdateLog: '12291 Improvement in menus
	https://pharo.fogbugz.com/f/cases/12291
	
11994 Remove MenuMorph inform:
	https://pharo.fogbugz.com/f/cases/11994
	
12303 Rename category in TabModel to Deprecated30
	https://pharo.fogbugz.com/f/cases/12303
	
12302 Move Compiler deprecated methods to Deprecated30 package again
	https://pharo.fogbugz.com/f/cases/12302
	
11439 Renaming --all-- protocol should not be possible
	https://pharo.fogbugz.com/f/cases/11439'.
	self loadTogether: self script268 merge: false.
	self flushCaches.
