update30636
	"self new update30636"
	self withUpdateLog: '- Issue 12390 MenuRegistation is bogus
	https://pharo.fogbugz.com/f/cases/12390/MenuRegistation-is-bogus
	
- Issue 12387 Finder displays too many strings around arguments
	https://pharo.fogbugz.com/f/cases/12387/Finder-displays-too-many-strings-around-arguments
	
- Issue 12393 MessageNotUnderstood: receiver of "ui" is nil
https://pharo.fogbugz.com/f/cases/12393/MessageNotUnderstood-receiver-of-ui-is-nil

- Issue 12383 Loose package selection on using package filter
	https://pharo.fogbugz.com/f/cases/12383/Loose-package-selection-on-using-package-filter'.
	self loadTogether: self script291 merge: false.
	self flushCaches.
