update30592
	"self new update30592"
	self withUpdateLog: '12227 Move System-Support deprecated methods to Deprecated30 package
	https://pharo.fogbugz.com/f/cases/12227
	
12198 should remove TimeStamp Step2
	https://pharo.fogbugz.com/f/cases/12198
	
12202 Exception Handling improvement to ignore some specific Exception
	https://pharo.fogbugz.com/f/cases/12202'.
	self loadTogether: self script247 merge: false.
	self flushCaches.
