update30398
	"self new update30398"
	self withUpdateLog: '11599 Transcript menu is broken
	https://pharo.fogbugz.com/f/cases/11599
	
11600 RBPlatform and RBPharoPlatform can be removed
	https://pharo.fogbugz.com/f/cases/11600
	
11604 remove more sender of #halt:
	https://pharo.fogbugz.com/f/cases/11604
	
11496 SpecDebugger close window keyboard shortcut not working when freshly opened
	https://pharo.fogbugz.com/f/cases/11496
	'.
	self loadTogether: self script190 merge: false.
	self flushCaches.
