update30682
	"self new update30682"
	self withUpdateLog: '12606 moving classes from A tag B to package A-B broken
	https://pharo.fogbugz.com/f/cases/12606
	
12607 Be able to filter dirty packages to display in Komitter
	https://pharo.fogbugz.com/f/cases/12607
	
12609 Remove the last non unit test users of TimeStamp
	https://pharo.fogbugz.com/f/cases/12609
	
12608 remove unnecesary crLog in SpecDebugger
	https://pharo.fogbugz.com/f/cases/12608'.
	self loadTogether: self script335 merge: false.
	self flushCaches.
