update30634
	"self new update30634"
	self withUpdateLog: '12376 Finder raises an error when right clicking on the main panel
	https://pharo.fogbugz.com/f/cases/12376
	
12380 The logic to retrieve the patch of KomitPackage should be extracted
	https://pharo.fogbugz.com/f/cases/12380
	
12378 On Unix, the shortcut to validate the Komitter window is not working
	https://pharo.fogbugz.com/f/cases/12378
	
12375 PluggableButtonMorph error on getMenuSelector
	https://pharo.fogbugz.com/f/cases/12375'.
	self loadTogether: self script289 merge: false.
	self flushCaches.
