update30625
	"self new update30625"
	self withUpdateLog: '12355 Adapters should inherit form Model
	https://pharo.fogbugz.com/f/cases/12355
	
12344 Cleanup on some Keymapping methods
	https://pharo.fogbugz.com/f/cases/12344
	
11817 MorphTreeMorph draws wrongly when it is outside the screen
	https://pharo.fogbugz.com/f/cases/11817'.
	self loadTogether: self script280 merge: false.
	self flushCaches.
