update30545
	"self new update30545"
	self withUpdateLog: '- Issue 12066: Add Image support in Spec
	https://pharo.fogbugz.com/f/cases/12066/Add-Image-support
	Thanks Benjamin van Ryseghem and Sergi Reyner
	
- Issue 12056: flatCollect: should return the same species
	https://pharo.fogbugz.com/f/cases/12066/Add-Image-support
	
- Issue 11895 Theme: Dont use Gradients in menus
	https://pharo.fogbugz.com/f/cases/11895/Theme-Don-t-use-Gradients-in-menus
		UITheme current settings preferGradientFill: false.

- Issue 11427: Clean up SqNumberParser Hierarchy
	https://pharo.fogbugz.com/f/cases/11427/Clean-up-SqNumberParser-Hierarchy'.
	self loadTogether: self script200 merge: false.
	UITheme current settings preferGradientFill: false.
	self flushCaches.
