update30783
	"self new update30783"
	self withUpdateLog: '12997 Class comment missing for package PackageInfo
	https://pharo.fogbugz.com/f/cases/12997

12952 Context menu for dependentProjcts gives DNU for a new project
	https://pharo.fogbugz.com/f/cases/12952

13001 SystemWindow sendTopWindowToBack does not work when invoked from World menu or global shortcut
	https://pharo.fogbugz.com/f/cases/13001

12957 SimulateKeystrokesSpecification >> testSimulateCmdKeystroke failure 
	https://pharo.fogbugz.com/f/cases/12957

12976 Komitter provokes race-condition in MCMethodDefinition class>>#instanceLike:
	https://pharo.fogbugz.com/f/cases/12976

13015 Fix MessageBrowser button size
	https://pharo.fogbugz.com/f/cases/13015

'.
	self loadTogether: self script436 merge: false.
	self flushCaches.
