update30675
	"self new update30675"
	self withUpdateLog: '12568 IconicListItem should lock text morph
	https://pharo.fogbugz.com/f/cases/12568
	
12567 PluggableButtonMorph should clip submorphs
	https://pharo.fogbugz.com/f/cases/12567
	
12516 Nautilus find methode ... does not select the method
	https://pharo.fogbugz.com/f/cases/12516
	
12582 Silly code in PluggableListMorph
	https://pharo.fogbugz.com/f/cases/12582'.
	self loadTogether: self script328 merge: false.
	self flushCaches.
