update30756
	"self new update30756"
	self withUpdateLog: '12871 Class comments missing for Settings-... packages
	https://pharo.fogbugz.com/f/cases/12871

12024 ExtractAll does not work for a .mcz in a FileList
	https://pharo.fogbugz.com/f/cases/12024

12829 Dragging a morph to system browser results in DNU >> #passenger
	https://pharo.fogbugz.com/f/cases/12829

'.
	self loadTogether: self script409 merge: false.
	self flushCaches.
