update30455
	"self new update30455"
	self withUpdateLog: '11790 add critic rule for keys do: -> keysDo: (and valuesDo:)
	https://pharo.fogbugz.com/f/cases/11790
	
11787 Trivial critic cleanup of CodeImport
	https://pharo.fogbugz.com/f/cases/11787
	
11793 Package Support on RBBrowserEnvironment	
	https://pharo.fogbugz.com/f/cases/11793
	
11792 First simplistic file system tree inspector
	https://pharo.fogbugz.com/f/cases/11792'.
	self loadTogether: self script110 merge: false.
	self flushCaches.
