update30542
	"self new update30542"
	self withUpdateLog: '12057 #localSelectors: can be implemented in TBehavior
	https://pharo.fogbugz.com/f/cases/12057
	
12058 Move all the old Url Classes to Deprecated30
	https://pharo.fogbugz.com/f/cases/12058
	
12050 KM modification to make plateform specific shortcuts work when defined without pragmas
	https://pharo.fogbugz.com/f/cases/12050'.
	self loadTogether: self script197 merge: false.
	self flushCaches.
