update30505
	"self new update30505"
	self withUpdateLog: '11519 Merge Color and Translucent Color - post publication
	https://pharo.fogbugz.com/f/cases/11519
	
11951 Cannot access in text editors to temporaries in context inspectors. Thanks Clement Bera
	https://pharo.fogbugz.com/f/cases/11951
	
11311 Rewrite Object class comment
	https://pharo.fogbugz.com/f/cases/11311'.
	self loadTogether: self script160 merge: false.
	self flushCaches.
