update30619
	"self new update30619"
	self withUpdateLog: '12077 MNU in AdditionalMethodState>>analogousCodeTo:
	https://pharo.fogbugz.com/f/cases/12077

12319 Replace includesAllOf: by includesAll: everywhere.
	https://pharo.fogbugz.com/f/cases/12319
	
12332 New icons for remotes + ui centered at opening
	https://pharo.fogbugz.com/f/cases/12332
	
12284 Problem with credential
	https://pharo.fogbugz.com/f/cases/12284
'.
	self loadTogether: self script274 merge: false.
	self flushCaches.
