update30363
	"self new update30363"
	self withUpdateLog: '11524 MessageBrowser new protocol method
	https://pharo.fogbugz.com/f/cases/11524
	
11523 SystemNavigation small refactoring
	https://pharo.fogbugz.com/f/cases/11523
	
11498 Be able to set an initial filter in ListDialogWindow
	https://pharo.fogbugz.com/f/cases/11498
	
11522 NewList separator support
	https://pharo.fogbugz.com/f/cases/11522'.
	self loadTogether: self script155 merge: false.
	self flushCaches.
