update30493
	"self new update30493"
	self withUpdateLog: '11912 faster #allMethods on SystemNavigation
	https://pharo.fogbugz.com/f/cases/11912
	
11894 Tests.Release.ReleaseTest.testKernelExtensions fails
	https://pharo.fogbugz.com/f/cases/11894
	
11909 MorphTreeMorph lacks enable/disable
	https://pharo.fogbugz.com/f/cases/11909
	
11886 Typo at method name: RBMoveMethodRefactor>>compileDelagatorMethod
	https://pharo.fogbugz.com/f/cases/11886'.
	self loadTogether: self script148 merge: false.
	self flushCaches.
