update30317
	"self new update30317"
	self withUpdateLog: '11269 isNil ifTrue: to ifNil: part 9
	https://pharo.fogbugz.com/f/cases/11269
	
11277 isNil ifTrue: to: ifNil: Morphic Kernel
	https://pharo.fogbugz.com/f/cases/11277
	
11272 isNil ifTrue: to ifNil: part 12 (last before morphic)
	https://pharo.fogbugz.com/f/cases/resolve/11272
'.
	self loadTogether: self script110 merge: false.
	self flushCaches.
