update30656
	"self new update30656"
	self withUpdateLog: '11403 --all-- protocol disappears when browsing scoped
	https://pharo.fogbugz.com/f/cases/11403
	
12468 KernelTests packages are messed up on changes
	https://pharo.fogbugz.com/f/cases/12468
	
12392 EyeInspector should not depend on Nautilus
	https://pharo.fogbugz.com/f/cases/12392
	
12381 Creating slices is broken
	https://pharo.fogbugz.com/f/cases/12381'.
	self loadTogether: self script309 merge: false.
	self flushCaches.
