update30529
	"self new update30529"
	self withUpdateLog: '11673 No timestamp in MCMethodDefinition>>=
	https://pharo.fogbugz.com/f/cases/11673
	
12020 Optimize PNG reading for larger files
	https://pharo.fogbugz.com/f/cases/12020
	
11985 Code duplication for accessing as read-only the SourceFiles
	https://pharo.fogbugz.com/f/cases/11985'.
	self loadTogether: self script184 merge: false.
	self flushCaches.
