update30853
	"self new update30853"
	self withUpdateLog: '13796 DNU ReadWriteStream>>fileIn in SmalltalkEditor>>fileItIn
	https://pharo.fogbugz.com/f/cases/13796

13658 backport 3.0: 13654 Pressing Enter in EyeInspector gives MNU: TextModel>>asText
	https://pharo.fogbugz.com/f/cases/13658

13626 SelectorException>>signalFor:In: does not understand object:
	https://pharo.fogbugz.com/f/cases/13626

'.
	self loadTogether: self script115 merge: false.
	self flushCaches.
