update30365
	"self new update30365"
	self withUpdateLog: '11444 Improving MiniKernel
	https://pharo.fogbugz.com/f/cases/11444
	
11507 NautilusAbstractUI should be accept different classifiers
	https://pharo.fogbugz.com/f/cases/11507
	(This was alreay in, at least I did not see any changes when merging)
	
11148 shouldnt:raise: should not be used
	https://pharo.fogbugz.com/f/cases/11148'.
	self loadTogether: self script157 merge: false.
	self flushCaches.
