update30368
	"self new update30368"
	self withUpdateLog: '11530 AbstractNautilusUI >> categorizeAllUncategorizedMethods broken
	https://pharo.fogbugz.com/f/cases/11530
	
11497 pharo CI.image --list shows empty entry for default command line handler
	https://pharo.fogbugz.com/f/cases/11497
	
11528 Harden FileDirectoryWrapper
	https://pharo.fogbugz.com/f/cases/11528'.
	self loadTogether: self script160 merge: false.
	self flushCaches.
