update30797
	"self new update30797"
	self withUpdateLog: '13064 nil as menutitle (inspector menu)
	https://pharo.fogbugz.com/f/cases/13064

13032 Transcript red screen of death
	https://pharo.fogbugz.com/f/cases/13032

12103 shortcuts for tools
	https://pharo.fogbugz.com/f/cases/12103

13062 Scroll does not work in Monticello package list
	https://pharo.fogbugz.com/f/cases/13062

13066 Failing tests in NetworkTests.Url.UrlTest
	https://pharo.fogbugz.com/f/cases/13066

'.
	self loadTogether: self script450 merge: false.
	self flushCaches.
