update30454
	"self new update30454"
	self withUpdateLog: '11768 Small Code Critic cleanup of UpdateStreamer
	https://pharo.fogbugz.com/f/cases/11768
	
11785 add menu entry to run cleanup in the system menu
	https://pharo.fogbugz.com/f/cases/11785
	
11726 Code Critic: Variable used but not defined anywhere is wrong
	https://pharo.fogbugz.com/f/cases/11726'.
	self loadTogether: self script109 merge: false.
	self flushCaches.
