update30628
	"self new update30628"
	self withUpdateLog: '12308 GroupManager looks useless
	https://pharo.fogbugz.com/f/cases/12308
	
12348 Cleanup on some Fuel methods
	https://pharo.fogbugz.com/f/cases/12348
	
12362 Restrict the RemotesManager to the dirty packages
	https://pharo.fogbugz.com/f/cases/12362
	
12360 Add missing protocol to SearchableTree
	https://pharo.fogbugz.com/f/cases/12360
	
12359 Add missing protocol to OkToolbar
	https://pharo.fogbugz.com/f/cases/12359'.
	self loadTogether: self script283 merge: false.
	self flushCaches.
