update30559
	"self new update30559"
	self withUpdateLog: '12117 Fix NewList >> #allowToSelect to use new ValueHolder API
	https://pharo.fogbugz.com/f/cases/12117
	
12048 Incorporate Ring extension methods in SourceFileArray
	https://pharo.fogbugz.com/f/cases/12048
	
12104 Optimize Dictionary>>valuesDo:, part 2
	https://pharo.fogbugz.com/f/cases/12104
	
12072 Get rid of last hardcoded references to TransferMorph
	https://pharo.fogbugz.com/f/cases/12072'.
	self loadTogether: self script215 merge: false.
	self flushCaches.
