update30740
	"self new update30740"
	self withUpdateLog: '12778 NB generated code user initials
	https://pharo.fogbugz.com/f/cases/12778

12788 Please review  ProtocolClient(class)>>retrieveMIMEDocument:
	https://pharo.fogbugz.com/f/cases/12788

12781 Class comment missing for package Compression
	https://pharo.fogbugz.com/f/cases/12781

12787 Class comment missing in package Morphic-Examples
	https://pharo.fogbugz.com/f/cases/12787

12785 Class comment missing in Smart suggestions package
	https://pharo.fogbugz.com/f/cases/12785

12784 Class comment missing in File package
	https://pharo.fogbugz.com/f/cases/12784

12737 Morph sends mouseUp twice to handlers
	https://pharo.fogbugz.com/f/cases/12737

12782 Class comments missing in Deprecated package
	https://pharo.fogbugz.com/f/cases/12782

12783 Class comments missing in Fuel package
	https://pharo.fogbugz.com/f/cases/12783

'.
	self loadTogether: self script393 merge: false.
	self flushCaches.
