update30617
	"self new update30617"
	self withUpdateLog: '12321 less senders of #methodDict
	https://pharo.fogbugz.com/f/cases/12321
	
12328 TreeInspector DNU
	https://pharo.fogbugz.com/f/cases/12328
	
12314 Add a view to link/add new remotes
	https://pharo.fogbugz.com/f/cases/12314
	
12325 HaloMorph >> #worldBoundsForMorph: calls deprecated outsetBy:
	https://pharo.fogbugz.com/f/cases/12325
	
12312 Cleanup on some Morphic methods
	https://pharo.fogbugz.com/f/cases/12312'.
	self loadTogether: self script272 merge: false.
	self flushCaches.
