update30762
	"self new update30762"
	self withUpdateLog: '12843 MessageNotUnderstood: MCDirectoryRepository>>koRemote
	https://pharo.fogbugz.com/f/cases/12843

12591 Nautilus: Class Pane Update after DND
	https://pharo.fogbugz.com/f/cases/12591

12881 Failing tests for Shortcuts on Mac
	https://pharo.fogbugz.com/f/cases/12881

'.
	self loadTogether: self script415 merge: false.
	self flushCaches.
