update30458
	"self new update30458"
	self withUpdateLog: '11804 Small cleanup in SystemNavigation
	https://pharo.fogbugz.com/f/cases/11804
	(from me)
	
11806 Refactor the Create action for #doesNotUnderstand
	https://pharo.fogbugz.com/f/cases/11806
	(from Andrei)
	
11805 [ENH] Editor skip over multiple white space (+ setting option)
	https://pharo.fogbugz.com/f/cases/11805
	(From Igor)'.
	self loadTogether: self script113 merge: false.
	self flushCaches.
