update30587
	"self new update30587"
	self withUpdateLog: '12158 Give a way to access parent node in a TreeNodeModel
	https://pharo.fogbugz.com/f/cases/12158
	
6987 Strange protocol: #allSelectorsWithout: + autocompletion + traits
	https://pharo.fogbugz.com/f/cases/6987
	
12206 Move FileSystem-Core deprecated methods to Deprecated30 package
	https://pharo.fogbugz.com/f/cases/12206
	
12207 Move Traits deprecated methods to Deprecated30 package
	https://pharo.fogbugz.com/f/cases/12207'.
	self loadTogether: self script242 merge: false.
	self flushCaches.
