update30663
	"self new update30663"
	self withUpdateLog: '12510 NautilusHistory entry for class methods loads instance methods
	https://pharo.fogbugz.com/f/cases/12510
	
12502 FileList MNU FileSystemPermission>><=
	https://pharo.fogbugz.com/f/cases/12502
	
12429 MessageBrowser loses changes
	https://pharo.fogbugz.com/f/cases/12429
	
12451 Error on Browse Full in Nautilus from class in group view
	https://pharo.fogbugz.com/f/cases/12451
	'.
	self loadTogether: self script316 merge: false.
	self flushCaches.
