update30629
	"self new update30629"
	self withUpdateLog: '12315 Menu World/System/Switch User raises Error and MNU
	https://pharo.fogbugz.com/f/cases/12315
	
12361 Bug in MorphTreeMorph if click is made on no item
	https://pharo.fogbugz.com/f/cases/12361
	
12345 Cleanup on more Opal methods
	https://pharo.fogbugz.com/f/cases/12345'.
	self loadTogether: self script284 merge: false.
	self flushCaches.
