update30668
	"self new update30668"
	self withUpdateLog: '12540 PackageDependencyTest has no testmethods
	https://pharo.fogbugz.com/f/cases/12540
	
12498 ClassDescription appears twice in <Hierarchical> view
	https://pharo.fogbugz.com/f/cases/12498
	
12527 Add as Group creates an unbrowsable group
	https://pharo.fogbugz.com/f/cases/12527
	
11811 GroupWindowMorph class definition not evaluable
	https://pharo.fogbugz.com/f/cases/11811'.
	self loadTogether: self script321 merge: false.
	self flushCaches.
