update30591
	"self new update30591"
	self withUpdateLog: '12225 Enhancement in MorphTreeMorph
	https://pharo.fogbugz.com/f/cases/12225
	
12226 Minor additions
	https://pharo.fogbugz.com/f/cases/12226
	
12224 Move Kernel deprecated methods to Deprecated30 package
	https://pharo.fogbugz.com/f/cases/12224
	
12228 Move Compiler deprecated methods to Deprecated30 package
	https://pharo.fogbugz.com/f/cases/12228'.
	self loadTogether: self script246 merge: false.
	self flushCaches.
