update30506
	"self new update30506"
	self withUpdateLog: '11950 Context menu does not work with Spec inspector
	https://pharo.fogbugz.com/f/cases/11950
	
11610 Failing test KMDispatcherTestCase>>#testAttach
	https://pharo.fogbugz.com/f/cases/11610
	
11772 as yet unclassified protocol remains when empty
	https://pharo.fogbugz.com/f/cases/11772
	
11952 Improve NautilusHistory by adding unsaved states in it
	https://pharo.fogbugz.com/f/cases/11952'.
	self loadTogether: self script161 merge: false.
	self flushCaches.
