update30804
	"self new update30804"
	self withUpdateLog: '13128 Use Spotlight to quickly evaluate and inspect short expressions 
	https://pharo.fogbugz.com/f/cases/13128

13101 Progress bar progressive text update not working.
	https://pharo.fogbugz.com/f/cases/13101

13137 Replace SBCI buttons
	https://pharo.fogbugz.com/f/cases/13137
	
3748 FloatArray>>dot: is defined in plugin but not at the image level
	https://pharo.fogbugz.com/f/cases/3748/

'.
	self loadTogether: self script457 merge: false.
	self flushCaches.
