update30571
	"self new update30571"
	self withUpdateLog: '12156 Move code in SmalltalkImage>>closeSourceFiles to SourceFileArray
	https://pharo.fogbugz.com/f/cases/12156
	
10890 Converting FileUrl w. spaces to FileReference (was Load configs from local folders)
	https://pharo.fogbugz.com/f/cases/10890
	
12150 Better Menu support
	https://pharo.fogbugz.com/f/cases/12150'.
	self loadTogether: self script227 merge: false.
	self flushCaches.
