update30624
	"self new update30624"
	self withUpdateLog: '12252 Canceling Save As... triggers a MNU
	https://pharo.fogbugz.com/f/cases/12252
	
12353 MorphTreeMorph should allow to click on the checkbox
	https://pharo.fogbugz.com/f/cases/12353
	
7365 Either remove or run MCWorkingCopyBrowser>>checkForNewerVersions
	https://pharo.fogbugz.com/f/cases/7365
	
12339 Cleanup on some Font methods
	https://pharo.fogbugz.com/f/cases/12339'.
	self loadTogether: self script279 merge: false.
	self flushCaches.
