update30428
	"self new update30428"
	self withUpdateLog: '11703 #debugError: should be implemented on Smalltalk tools debugger, not Smalltalk tools
	https://pharo.fogbugz.com/f/cases/11703
	
11702 spelling error transferred
	https://pharo.fogbugz.com/f/cases/11702
	
11660 Use specific Spec model methods
	https://pharo.fogbugz.com/f/cases/11660'.
	self loadTogether: self script107 merge: false.
	self flushCaches.
