update30751
	"self new update30751"
	self withUpdateLog: '12833 IconicListItem does not give visual feedback about the enablement status
	https://pharo.fogbugz.com/f/cases/12833

12628 KeyNotFound in RPackage>>methods in the presence of anonymous classes
	https://pharo.fogbugz.com/f/cases/12628

12739 Class definition NOT available in the "Recover Lost Changes" tool
	https://pharo.fogbugz.com/f/cases/12739

'.
	self loadTogether: self script404 merge: false.
	self flushCaches.
