update30794
	"self new update30794"
	self withUpdateLog: '13052 EyeTreeInspector does not respect the description of EyeDynamicElement
	https://pharo.fogbugz.com/f/cases/13052

13058 Smalltalk tools explore does not work where Smalltalk tools inspect does.
	https://pharo.fogbugz.com/f/cases/13058

12989 Zn Update
	https://pharo.fogbugz.com/f/cases/12989/'.
	self loadTogether: self script447 merge: false.
	self flushCaches.
