update30770
	"self new update30770"
	self withUpdateLog: '12905 Completion is bugging under Linux/Ubuntu 13.04 with factorial method
	https://pharo.fogbugz.com/f/cases/12905

12919 Beeper>>#beepPrimitive calls deprecated code
	https://pharo.fogbugz.com/f/cases/12919

11434 Nautilus should keep the scroll position in list of methods
	https://pharo.fogbugz.com/f/cases/11434

12913 Issue in IconicListItem
	https://pharo.fogbugz.com/f/cases/12913

12872 Issues with resolving parent Path
	https://pharo.fogbugz.com/f/cases/12872

'.
	self loadTogether: self script423 merge: false.
	self flushCaches.
