update30382
	"self new update30382"
	self withUpdateLog: '11549 PluggableTextMorph closes completion menu on keydown
	https://pharo.fogbugz.com/f/cases/11549
	
11543 Select protocol name with suggestions
	https://pharo.fogbugz.com/f/cases/11543
	
11556 subclassResponsability -> subclassResponsibility
	https://pharo.fogbugz.com/f/cases/11556
'.
	self loadTogether: self script174 merge: false.
	self flushCaches.
