update30696
	"self new update30696"
	self withUpdateLog: '12625 toggling hierarchy/flat shows wrong package and hides selected class
	https://pharo.fogbugz.com/f/cases/12625
	
12647 NativeBoost: two tests failing on windows
	https://pharo.fogbugz.com/f/cases/12647
	
12642 bug in NumberParser when reading a number with fraction part
	https://pharo.fogbugz.com/f/cases/12642'.
	self loadTogether: self script349 merge: false.
	self flushCaches.
