update30528
	"self new update30528"
	self withUpdateLog: '12019 Optimize Dictionary>>#includesKey:
	https://pharo.fogbugz.com/f/cases/12019
	
12018 Gofer failing due to ZnUrl missing mcRepositoryAsUser:withPassword:
	https://pharo.fogbugz.com/f/cases/12018
	
11989 shouldnt:raise: Error from issue #11876 is too offensive
	https://pharo.fogbugz.com/f/cases/11989'.
	self loadTogether: self script183 merge: false.
	self flushCaches.
