update30638
	"self new update30638"
	self withUpdateLog: '12409 DNU RPackage>>#item when FileOut
	https://pharo.fogbugz.com/f/cases/12409
	
12402 Display reverse: leads to error
	https://pharo.fogbugz.com/f/cases/12402
	
12384 Package filter dialog: Make the feature more apparent
	https://pharo.fogbugz.com/f/cases/12384
	
12396 SystemNavigation class comment uses deprecated message
	https://pharo.fogbugz.com/f/cases/12396
	
12094 Drop down does show the items wrongly
	https://pharo.fogbugz.com/f/cases/12094'.
	self loadTogether: self script293 merge: false.
	self flushCaches.
