update30620
	"self new update30620"
	self withUpdateLog: '12272 Better algorithm for finding the inbox
	https://pharo.fogbugz.com/f/cases/12272
	
12334 Nautilus codepane hides first lines if pin is set
	https://pharo.fogbugz.com/f/cases/12334
	
11423 Running unit tests that raise deprecation warnings makes them fail incomprehensibly
	https://pharo.fogbugz.com/f/cases/11423'.
	self loadTogether: self script275 merge: false.
	self flushCaches.
