update30607
	"self new update30607"
	self withUpdateLog: '12269 Add support for easily centering a window
	https://pharo.fogbugz.com/f/cases/12269
	
12270 Remove unused TreeNode classes
	https://pharo.fogbugz.com/f/cases/12270
	
12275 RxsCharSet>>isEnumerable must be using anySatisfy
	https://pharo.fogbugz.com/f/cases/12275
	
12267 Nautilus Search Bar should not resize
	https://pharo.fogbugz.com/f/cases/12267'.
	self loadTogether: self script262 merge: false.
	self flushCaches.
