update30623
	"self new update30623"
	self withUpdateLog: '12346 Cleanup on some Nautilus methods
	https://pharo.fogbugz.com/f/cases/12346
	
12351 ChangesBrowser is broken
	https://pharo.fogbugz.com/f/cases/12351
	
12350 Rendering artifacts on shrinking SystemWindows
	https://pharo.fogbugz.com/f/cases/12350
	
12343 Cleanup on some UI methods
	https://pharo.fogbugz.com/f/cases/12343'.
	self loadTogether: self script278 merge: false.
	self flushCaches.
