update30550
	"self new update30550"
	self withUpdateLog: '11739 STCommandLineHandler cannot save
	https://pharo.fogbugz.com/f/cases/11739
	
6155 Locale plugin returning wrong isoCountry code
	https://pharo.fogbugz.com/f/cases/6155
	
11393 allFileNamesOrCache seems to be inconsistent with other methods
	https://pharo.fogbugz.com/f/cases/11393'.
	self loadTogether: self script205 merge: false.
	self flushCaches.
