update30699
	"self new update30699"
	self withUpdateLog: '12661 KeyboardEvent>>#storeOn: broken
	https://pharo.fogbugz.com/f/cases/12661

12660 MCPackage reviving  RPackage when it shouldn''t
	https://pharo.fogbugz.com/f/cases/12660

12659 Add Toggle full screen mode to World Windows menu
	https://pharo.fogbugz.com/f/cases/12659'.
	self loadTogether: self script352 merge: false.
	self flushCaches.
