update30466
	"self new update30466"
	self withUpdateLog: '7416 SystemNavigation should return CompiledMethod or RGMethodDefinition
	https://pharo.fogbugz.com/f/cases/7416
	
11829 Small critic cleanup in Network
	https://pharo.fogbugz.com/f/cases/11829
	
11830 Small Critic Cleanup in System-Support
	https://pharo.fogbugz.com/f/cases/11830'.
	self loadTogether: self script121 merge: false.
	self flushCaches.
