update30488
	"self new update30488"
	self withUpdateLog: '11896 Sorted methods in FileContentsBrowser
	https://pharo.fogbugz.com/f/cases/11896
	
11892 Small critic cleanup of Tools
	https://pharo.fogbugz.com/f/cases/11892
	
11897 Move KMRepository deprecated methods to Deprecated30 package
	https://pharo.fogbugz.com/f/cases/11897
	
11885 Inspector double click not working
	https://pharo.fogbugz.com/f/cases/11885'.
	self loadTogether: self script143 merge: false.
	self flushCaches.
