update30615
	"self new update30615"
	self withUpdateLog: '12307 Adding unload to GroupManager or GroupAbstract
	https://pharo.fogbugz.com/f/cases/12307
	
12273 DNU doing senders in Finder
	https://pharo.fogbugz.com/f/cases/12273
	
12305 resetGroups should be moved in superclass
	https://pharo.fogbugz.com/f/cases/12305
	
12299 #date:time: fix for 3.0
	https://pharo.fogbugz.com/f/cases/12299'.
	self loadTogether: self script270 merge: false.
	self flushCaches.
