update30407
	"self new update30407"
	self withUpdateLog: '11631 Disable History navigation buttons in Inspectors when not usable
	https://pharo.fogbugz.com/f/cases/11631
	
11413 Make a diff tool to show recategorization as a change properly
	https://pharo.fogbugz.com/f/cases/11413
	
11632 Add browse shortcut to critics browser	
	https://pharo.fogbugz.com/f/cases/11632'.
	self loadTogether: self script199 merge: false.
	Smalltalk ui icons initialize.
.
	self flushCaches.
