update30546
	"self new update30546"
	self withUpdateLog: '12052 Fuel could store LargeNegativeInteger up to 32bits magnitude
	https://pharo.fogbugz.com/f/cases/12052
	
12067 A TextAnchor should never try to placeEmbeddedObject: by itself
	https://pharo.fogbugz.com/f/cases/12067
	
11906 HDTestReport measures the wrong duration
	https://pharo.fogbugz.com/f/cases/11906'.
	self loadTogether: self script201 merge: false.
	self flushCaches.
