update30394
	"self new update30394"
	self withUpdateLog: '11575 Add a Spec model for DiffMorph
	https://pharo.fogbugz.com/f/cases/11575
	
11533 Change testEnsureDeleted into testEnsureDelete
	https://pharo.fogbugz.com/f/cases/11533
	
11593 MCMergeOrLoadWarning actions should use #resume: instead of #return
	https://pharo.fogbugz.com/f/cases/11593'.
	self loadTogether: self script186 merge: false.
	self flushCaches.
