update30746
	"self new update30746"
	self withUpdateLog: '12514 OCSemanticWarnings ignore "cancel" from a confirmation dialog
	https://pharo.fogbugz.com/f/cases/12514

12824 Class comment missing for package ConfigurationCommandLineHandler
	https://pharo.fogbugz.com/f/cases/12824

12512 SemanticAnalyzer ignores answer from UnknownSelectorWarning 
	https://pharo.fogbugz.com/f/cases/12512

12442 Nautilus brakes code when removing more than one unused local variables
	https://pharo.fogbugz.com/f/cases/12442

12823 Class comment missing in Monticello package
	https://pharo.fogbugz.com/f/cases/12823

'.
	self loadTogether: self script399 merge: false.
	self flushCaches.
