update30659
	"self new update30659"
	self withUpdateLog: '12477 Move MethodFinder old tests from code to TestsPackages
	https://pharo.fogbugz.com/f/cases/12477
	
12055 The Spec Debugger should not require the registered inspector to be built on Spec
	https://pharo.fogbugz.com/f/cases/12055

11743 Debugger fix the key shortcuts
	https://pharo.fogbugz.com/f/cases/11743'.
	self loadTogether: self script312 merge: false.
	self flushCaches.
