update30360
	"self new update30360"
	self withUpdateLog: '- issue 11508  Fixing expandBy: to take into account PointPair (issue 2489 part three)
	https://pharo.fogbugz.com/default.asp?11508
	
- issue 11507 NautilusAbstractUI should be accept different classifiers
	https://pharo.fogbugz.com/default.asp?11507
	
- issue 11503 rename Methods into selectors
	https://pharo.fogbugz.com/default.asp?11503'.
	self loadTogether: self script152 merge: false.
	self flushCaches.
